const PREGUNTAS = [
  {
    pregunta: "¿Cuál es la capital de Argentina?",
    categoria: "Geografía",
    opcion_a: "Rosario",
    opcion_b: "Buenos Aires",
    opcion_c: "La Plata",
    respuesta_correcta: "b"
  },
  {
    pregunta: "¿Quién escribió El Martín Fierro?",
    categoria: "Cultura General",
    opcion_a: "Jorge Luis Borges",
    opcion_b: "José Hernández",
    opcion_c: "Julio Cortázar",
    respuesta_correcta: "b"
  },
  {
    pregunta: "¿Cuántos jugadores hay en un equipo de fútbol?",
    categoria: "Deportes",
    opcion_a: "10",
    opcion_b: "11",
    opcion_c: "12",
    respuesta_correcta: "b"
  },
  {
    pregunta: "¿En qué continente está Argentina?",
    categoria: "Geografía",
    opcion_a: "América del Sur",
    opcion_b: "Europa",
    opcion_c: "Oceanía",
    respuesta_correcta: "a"
  },
  {
    pregunta: "¿Qué planeta es conocido como el planeta rojo?",
    categoria: "Ciencia",
    opcion_a: "Venus",
    opcion_b: "Marte",
    opcion_c: "Júpiter",
    respuesta_correcta: "b"
  },
  {
    pregunta: "¿Quién fue el primer presidente argentino?",
    categoria: "Historia",
    opcion_a: "Julio A. Roca",
    opcion_b: "Bernardino Rivadavia",
    opcion_c: "Sarmiento",
    respuesta_correcta: "b"
  },
  {
    pregunta: "¿Qué selección ganó el Mundial 2022?",
    categoria: "Deportes",
    opcion_a: "Francia",
    opcion_b: "Brasil",
    opcion_c: "Argentina",
    respuesta_correcta: "c"
  },
  {
    pregunta: "¿Cuál es el idioma oficial de Argentina?",
    categoria: "Cultura General",
    opcion_a: "Portugués",
    opcion_b: "Español",
    opcion_c: "Italiano",
    respuesta_correcta: "b"
  },
  {
    pregunta: "¿Qué instrumento tocaba Charly García?",
    categoria: "Cultura General",
    opcion_a: "Batería",
    opcion_b: "Teclado",
    opcion_c: "Violín",
    respuesta_correcta: "b"
  },
  {
    pregunta: "¿Cuántos días tiene un año bisiesto?",
    categoria: "Ciencia",
    opcion_a: "365",
    opcion_b: "366",
    opcion_c: "364",
    respuesta_correcta: "b"
  },
  { pregunta:"¿Cuál es la montaña más alta de Argentina?", categoria:"Geografía", opcion_a:"Cerro Mercedario", opcion_b:"Aconcagua", opcion_c:"Ojos del Salado", respuesta_correcta:"b"},
  { pregunta:"¿Qué bebida tradicional argentina se toma en mate?", categoria:"Cultura General", opcion_a:"Té", opcion_b:"Yerba mate", opcion_c:"Café", respuesta_correcta:"b"},
  { pregunta:"¿Cuál es el baile típico argentino originado en Buenos Aires?", categoria:"Cultura general", opcion_a:"Salsa", opcion_b:"Tango", opcion_c:"Cumbia", respuesta_correcta:"b"},
  { pregunta:"¿En qué provincia se encuentran las Cataratas del Iguazú?", categoria:"Geografía", opcion_a:"Misiones", opcion_b:"Corrientes", opcion_c:"Chaco", respuesta_correcta:"a"},
  { pregunta:"¿Quién es conocido como 'El Diego' en el fútbol argentino?", categoria:"Deportes", opcion_a:"Lionel Messi", opcion_b:"Diego Maradona", opcion_c:"Ángel Di María", respuesta_correcta:"b"},
  { pregunta:"¿Cuál es la capital de la provincia de Córdoba?", categoria:"Geografía", opcion_a:"Córdoba", opcion_b:"Villa María", opcion_c:"Río Cuarto", respuesta_correcta:"a"},
  { pregunta:"¿Qué animal es símbolo de la Patagonia argentina?", categoria:"Ciencia", opcion_a:"Cóndor", opcion_b:"Pingüino", opcion_c:"Guanaco", respuesta_correcta:"b"},
  { pregunta:"¿Quién fue Eva Perón, conocida como Evita?", categoria:"Historia", opcion_a:"Primera presidenta", opcion_b:"Esposa de Juan Perón", opcion_c:"Escritora famosa", respuesta_correcta:"b"},
  { pregunta:"¿En qué club jugó Lionel Messi casi toda su carrera antes de irse?", categoria:"Deportes", opcion_a:"River Plate", opcion_b:"Barcelona", opcion_c:"Boca Juniors", respuesta_correcta:"b"},
  { pregunta:"¿Cuál es el glaciar famoso en la Patagonia argentina?", categoria:"Geografía", opcion_a:"Perito Moreno", opcion_b:"Upsalla", opcion_c:"Viedma", respuesta_correcta:"a"},
  { pregunta:"¿Qué selección ganó la Copa América 2021?", categoria:"Deportes", opcion_a:"Brasil", opcion_b:"Argentina", opcion_c:"Uruguay", respuesta_correcta:"b"},
  { pregunta:"¿Cuál es la región sur de Argentina conocida por sus lagos y montañas?", categoria:"Geografía", opcion_a:"Pampa", opcion_b:"Patagonia", opcion_c:"Cuyo", respuesta_correcta:"b"},
  { pregunta:"¿Quién escribió 'El Aleph'?", categoria:"Cultura general", opcion_a:"Jorge Luis Borges", opcion_b:"Julio Cortázar", opcion_c:"Ernesto Sabato", respuesta_correcta:"a"},
  { pregunta:"¿En qué año se jugó la final del Mundial 1986 donde Maradona hizo 'La Mano de Dios'?", categoria:"Deportes", opcion_a:"1982", opcion_b:"1986", opcion_c:"1990", respuesta_correcta:"b"},
  { pregunta:"¿Cuál es la capital de la provincia de Mendoza?", categoria:"Geografía", opcion_a:"San Juan", opcion_b:"Mendoza", opcion_c:"San Luis", respuesta_correcta:"b"},
  { pregunta:"¿En qué provincia argentina está el Valle de la Luna?", categoria:"Geografía", opcion_a:"San Juan", opcion_b:"La Rioja", opcion_c:"Catamarca", respuesta_correcta:"a"},
  { pregunta:"¿Qué dulce típico argentino se hace con leche y azúcar quemada?", categoria:"Cultura general", opcion_a:"Alfajor", opcion_b:"Dulce de leche", opcion_c:"Pastafrola", respuesta_correcta:"b"},
  { pregunta:"¿Quién cantó 'De música ligera'?", categoria:"Cultura General", opcion_a:"Fito Páez", opcion_b:"Gustavo Cerati", opcion_c:"Luis Alberto Spinetta", respuesta_correcta:"b"},
  { pregunta:"¿Cuál es la flor nacional de Argentina?", categoria:"Ciencia", opcion_a:"Ceibo", opcion_b:"Jazmín del país", opcion_c:"Rosa", respuesta_correcta:"a"},
  { pregunta:"¿En qué año Argentina ganó su primer Mundial de fútbol?", categoria:"Deportes", opcion_a:"1978", opcion_b:"1986", opcion_c:"1974", respuesta_correcta:"a"},
  { pregunta:"¿Qué provincia argentina es conocida como 'la tierra del sol y del buen vino'?", categoria:"Geografía", opcion_a:"Salta", opcion_b:"Mendoza", opcion_c:"San Juan", respuesta_correcta:"b"},
  { pregunta:"¿Cómo se llama el postre de capas de dulce de leche, merengue y frutas?", categoria:"Cultura General", opcion_a:"Chocotorta", opcion_b:"Rogell", opcion_c:"Balcarce", respuesta_correcta:"c"},
  { pregunta:"¿Qué selección es el clásico rival de Argentina en fútbol?", categoria:"Deportes", opcion_a:"Uruguay", opcion_b:"Brasil", opcion_c:"Inglaterra", respuesta_correcta:"b"},
  { pregunta:"¿En qué ciudad argentina nació Lionel Messi?", categoria:"Deportes", opcion_a:"Buenos Aires", opcion_b:"Rosario", opcion_c:"Córdoba", respuesta_correcta:"b"},
  { pregunta:"¿Qué animal aparece en el escudo nacional argentino?", categoria:"Historia", opcion_a:"Cóndor", opcion_b:"Yaguareté", opcion_c:"Sol de Mayo", respuesta_correcta:"a"},
  { pregunta:"¿Cuál es la capital histórica de Argentina?", categoria:"Historia", opcion_a:"Tucumán", opcion_b:"Córdoba", opcion_c:"Buenos Aires", respuesta_correcta:"a"},
  { pregunta:"¿Qué banda de rock argentina cantaba 'Ji ji ji'?", categoria:"Cultura General", opcion_a:"Los Piojos", opcion_b:"Patricio Rey y sus Redonditos de Ricota", opcion_c:"Soda Stereo", respuesta_correcta:"b"},
  { pregunta:"¿En qué provincia está el Cerro Catedral?", categoria:"Geografía", opcion_a:"Neuquén", opcion_b:"Río Negro", opcion_c:"Chubut", respuesta_correcta:"b"},
  { pregunta:"¿Qué carne es la más típica en un asado argentino?", categoria:"Cultura General", opcion_a:"Pollo", opcion_b:"Chorizo y vacío", opcion_c:"Cerdo", respuesta_correcta:"b"},
  { pregunta:"¿Quién fue el Libertador que cruzó los Andes?", categoria:"Historia", opcion_a:"San Martín", opcion_b:"Belgrano", opcion_c:"Güemes", respuesta_correcta:"a"},
  { pregunta:"¿Qué río forma el límite natural entre Argentina y Uruguay?", categoria:"Geografía", opcion_a:"Paraná", opcion_b:"Río de la Plata", opcion_c:"Uruguay", respuesta_correcta:"c"},
  { pregunta:"¿Qué cantante argentina es conocida como 'La Negra'?", categoria:"Cultura General", opcion_a:"Mercedes Sosa", opcion_b:"Gilda", opcion_c:"María Elena Walsh", respuesta_correcta:"a"},
  { pregunta:"¿En qué año se proclamó la Independencia Argentina?", categoria:"Historia", opcion_a:"1810", opcion_b:"1816", opcion_c:"1853", respuesta_correcta:"b"},
  { pregunta:"¿Qué provincia argentina tiene la mayor cantidad de glaciares?", categoria:"Geografía", opcion_a:"Santa Cruz", opcion_b:"Chubut", opcion_c:"Tierra del Fuego", respuesta_correcta:"a"},
  { pregunta:"¿Qué equipo de fútbol argentino es conocido como 'Los Millonarios'?", categoria:"Deportes", opcion_a:"Boca Juniors", opcion_b:"River Plate", opcion_c:"Racing Club", respuesta_correcta:"b"},
  { pregunta:"¿Cuál es el árbol típico de la región pampeana?", categoria:"Ciencia", opcion_a:"Quebracho", opcion_b:"Ombú", opcion_c:"Araucaria", respuesta_correcta:"b"},
  { pregunta:"¿Qué escritor argentino ganó el Premio Nobel de Literatura?", categoria:"Cultura General", opcion_a:"Ninguno", opcion_b:"Jorge Luis Borges", opcion_c:"Ningún argentino lo ganó", respuesta_correcta:"c"},
  { pregunta:"¿En qué provincia está la Quebrada de Humahuaca?", categoria:"Geografía", opcion_a:"Salta", opcion_b:"Jujuy", opcion_c:"Tucumán", respuesta_correcta:"b"},
  { pregunta:"¿Qué jugador argentino ganó el Balón de Oro en 2023?", categoria:"Deportes", opcion_a:"Ángel Di María", opcion_b:"Lionel Messi", opcion_c:"Julián Álvarez", respuesta_correcta:"b"},
  { pregunta:"¿Qué bebida alcohólica argentina es famosa en todo el mundo?","categoria":"Cultura General", opcion_a:"Fernet con Coca", opcion_b:"Malbec", opcion_c:"Gancia", respuesta_correcta:"b"},
  { pregunta:"¿Qué ciudad argentina es conocida como 'La Docta'?", categoria:"Geografía", opcion_a:"Buenos Aires", opcion_b:"Córdoba", opcion_c:"La Plata", respuesta_correcta:"b"},
  { pregunta:"¿Quién compuso 'Alfonsina y el mar'?", categoria:"Cultura General", opcion_a:"Ariel Ramírez", opcion_b:"Félix Luna", opcion_c:"Ambos", respuesta_correcta:"c"},
  { pregunta:"¿Qué desierto ocupa gran parte de la Patagonia?", categoria:"Geografía", opcion_a:"Monte", opcion_b:"Patagónico", opcion_c:"Puna", respuesta_correcta:"b"},
  { pregunta:"¿Qué tenista argentino ganó Roland Garros en 2004?", categoria:"Deportes", opcion_a:"Juan Martín del Potro", opcion_b:"Guillermo Vilas", opcion_c:"Gastón Gaudio", respuesta_correcta:"c"},
  { pregunta:"¿En qué mes se celebra el Día de la Bandera en Argentina?", categoria:"Historia", opcion_a:"20 de junio", opcion_b:"9 de julio", opcion_c:"25 de mayo", respuesta_correcta:"a"},
    { pregunta:"¿En qué provincia argentina está el Valle de la Luna?", categoria:"Geografía", opcion_a:"San Juan", opcion_b:"La Rioja", opcion_c:"Catamarca", respuesta_correcta:"a"},
  { pregunta:"¿Qué dulce típico argentino se hace con leche y azúcar quemada?", categoria:"Cultura General", opcion_a:"Alfajor", opcion_b:"Dulce de leche", opcion_c:"Pastafrola", respuesta_correcta:"b"},
  { pregunta:"¿Quién cantó 'De música ligera'?", categoria:"Cultura General", opcion_a:"Fito Páez", opcion_b:"Gustavo Cerati", opcion_c:"Luis Alberto Spinetta", respuesta_correcta:"b"},
  { pregunta:"¿Cuál es la flor nacional de Argentina?", categoria:"Ciencia", opcion_a:"Ceibo", opcion_b:"Jazmín del país", opcion_c:"Rosa", respuesta_correcta:"a"},
  { pregunta:"¿En qué año Argentina ganó su primer Mundial de fútbol?", categoria:"Deportes", opcion_a:"1978", opcion_b:"1986", opcion_c:"1974", respuesta_correcta:"a"},
  { pregunta:"¿Qué provincia argentina es conocida como 'la tierra del sol y del buen vino'?", categoria:"Geografía", opcion_a:"Salta", opcion_b:"Mendoza", opcion_c:"San Juan", respuesta_correcta:"b"},
  { pregunta:"¿Cómo se llama el postre de capas de dulce de leche, merengue y frutas?", categoria:"Cultura General", opcion_a:"Chocotorta", opcion_b:"Rogell", opcion_c:"Balcarce", respuesta_correcta:"c"},
  { pregunta:"¿Qué selección es el clásico rival de Argentina en fútbol?", categoria:"Deportes", opcion_a:"Uruguay", opcion_b:"Brasil", opcion_c:"Inglaterra", respuesta_correcta:"b"},
  { pregunta:"¿En qué ciudad argentina nació Lionel Messi?", categoria:"Deportes", opcion_a:"Buenos Aires", opcion_b:"Rosario", opcion_c:"Córdoba", respuesta_correcta:"b"},
  { pregunta:"¿Qué animal aparece en el escudo nacional argentino?", categoria:"Historia", opcion_a:"Cóndor", opcion_b:"Yaguareté", opcion_c:"Sol de Mayo", respuesta_correcta:"a"},
  { pregunta:"¿Cuál es la capital histórica de Argentina?", categoria:"Historia", opcion_a:"Tucumán", opcion_b:"Córdoba", opcion_c:"Buenos Aires", respuesta_correcta:"a"},
  { pregunta:"¿Qué banda de rock argentina cantaba 'Ji ji ji'?", categoria:"Cultura General", opcion_a:"Los Piojos", opcion_b:"Patricio Rey y sus Redonditos de Ricota", opcion_c:"Soda Stereo", respuesta_correcta:"b"},
  { pregunta:"¿En qué provincia está el Cerro Catedral?", categoria:"Geografía", opcion_a:"Neuquén", opcion_b:"Río Negro", opcion_c:"Chubut", respuesta_correcta:"b"},
  { pregunta:"¿Qué carne es la más típica en un asado argentino?", categoria:"Cultura General", opcion_a:"Pollo", opcion_b:"Chorizo y vacío", opcion_c:"Cerdo", respuesta_correcta:"b"},
  { pregunta:"¿Quién fue el Libertador que cruzó los Andes?", categoria:"Historia", opcion_a:"San Martín", opcion_b:"Belgrano", opcion_c:"Güemes", respuesta_correcta:"a"},
  { pregunta:"¿Qué río forma el límite natural entre Argentina y Uruguay?", categoria:"Geografía", opcion_a:"Paraná", opcion_b:"Río de la Plata", opcion_c:"Uruguay", respuesta_correcta:"c"},
  { pregunta:"¿Qué cantante argentina es conocida como 'La Negra'?", categoria:"Cultura General", opcion_a:"Mercedes Sosa", opcion_b:"Gilda", opcion_c:"María Elena Walsh", respuesta_correcta:"a"},
  { pregunta:"¿En qué año se proclamó la Independencia Argentina?", categoria:"Historia", opcion_a:"1810", opcion_b:"1816", opcion_c:"1853", respuesta_correcta:"b"},
  { pregunta:"¿Qué provincia argentina tiene la mayor cantidad de glaciares?", categoria:"Geografía", opcion_a:"Santa Cruz", opcion_b:"Chubut", opcion_c:"Tierra del Fuego", respuesta_correcta:"a"},
  { pregunta:"¿Qué equipo de fútbol argentino es conocido como 'Los Millonarios'?", categoria:"Deportes", opcion_a:"Boca Juniors", opcion_b:"River Plate", opcion_c:"Racing Club", respuesta_correcta:"b"},
  { pregunta:"¿Cuál es el árbol típico de la región pampeana?", categoria:"Ciencia", opcion_a:"Quebracho", opcion_b:"Ombú", opcion_c:"Araucaria", respuesta_correcta:"b"},
  { pregunta:"¿Qué escritor argentino ganó el Premio Nobel de Literatura?", categoria:"Cultura General", opcion_a:"Ninguno", opcion_b:"Jorge Luis Borges", opcion_c:"Ningún argentino lo ganó", respuesta_correcta:"c"},
  { pregunta:"¿En qué provincia está la Quebrada de Humahuaca?", categoria:"Geografía", opcion_a:"Salta", opcion_b:"Jujuy", opcion_c:"Tucumán", respuesta_correcta:"b"},
  { pregunta:"¿Qué jugador argentino ganó el Balón de Oro en 2023?", categoria:"Deportes", opcion_a:"Ángel Di María", opcion_b:"Lionel Messi", opcion_c:"Julián Álvarez", respuesta_correcta:"b"},
  { pregunta:"¿Qué bebida alcohólica argentina es famosa en todo el mundo?","categoria":"Cultura General", opcion_a:"Fernet con Coca", opcion_b:"Malbec", opcion_c:"Gancia", respuesta_correcta:"b"},
  { pregunta:"¿Qué ciudad argentina es conocida como 'La Docta'?", categoria:"Geografía", opcion_a:"Buenos Aires", opcion_b:"Córdoba", opcion_c:"La Plata", respuesta_correcta:"b"},
  { pregunta:"¿Quién compuso 'Alfonsina y el mar'?", categoria:"Cultura General", opcion_a:"Ariel Ramírez", opcion_b:"Félix Luna", opcion_c:"Ambos", respuesta_correcta:"c"},
  { pregunta:"¿Qué desierto ocupa gran parte de la Patagonia?", categoria:"Geografía", opcion_a:"Monte", opcion_b:"Patagónico", opcion_c:"Puna", respuesta_correcta:"b"},
  { pregunta:"¿Qué tenista argentino ganó Roland Garros en 2004?", categoria:"Deportes", opcion_a:"Juan Martín del Potro", opcion_b:"Guillermo Vilas", opcion_c:"Gastón Gaudio", respuesta_correcta:"c"},
  { pregunta:"¿En qué mes se celebra el Día de la Bandera en Argentina?", categoria:"Historia", opcion_a:"20 de junio", opcion_b:"9 de julio", opcion_c:"25 de mayo", respuesta_correcta:"a"},
  { pregunta:"¿Qué provincia argentina es conocida como 'la madre de ciudades'?", categoria:"Geografía", opcion_a:"Santiago del Estero", opcion_b:"Tucumán", opcion_c:"Salta", respuesta_correcta:"a"},
  { pregunta:"¿Quién dirigió la película 'La historia oficial', ganadora del Oscar?", categoria:"Cultura General", opcion_a:"Fernando Solanas", opcion_b:"Luis Puenzo", opcion_c:"Juan José Campanella", respuesta_correcta:"b"},
  { pregunta:"¿Qué equipo de fútbol argentino es conocido como 'El Ciclón'?", categoria:"Deportes", opcion_a:"San Lorenzo", opcion_b:"Huracán", opcion_c:"Vélez Sarsfield", respuesta_correcta:"a"},
  { pregunta:"¿Cuál es el postre argentino hecho con galletitas, dulce de leche y queso crema?", categoria:"Cultura General", opcion_a:"Chocotorta", opcion_b:"Flan casero", opcion_c:"Pastafrola", respuesta_correcta:"a"},
  { pregunta:"¿En qué provincia argentina está el Talampaya?", categoria:"Geografía", opcion_a:"La Rioja", opcion_b:"San Juan", opcion_c:"Catamarca", respuesta_correcta:"a"},
  { pregunta:"¿Qué cantante de cuarteto es conocido como 'El Potro'?", categoria:"Cultura General", opcion_a:"Rodrigo Bueno", opcion_b:"Carlos Jiménez", opcion_c:"Walter Olmos", respuesta_correcta:"a"},
  { pregunta:"¿En qué año murió Diego Maradona?", categoria:"Deportes", opcion_a:"2019", opcion_b:"2020", opcion_c:"2021", respuesta_correcta:"b"},
  { pregunta:"¿Qué escritor argentino escribió 'Rayuela'?", categoria:"Cultura General", opcion_a:"Julio Cortázar", opcion_b:"Ernesto Sabato", opcion_c:"Adolfo Bioy Casares", respuesta_correcta:"a"},
  { pregunta:"¿Qué isla argentina es la más austral del mundo (excluyendo la Antártida)?", categoria:"Geografía", opcion_a:"Isla de los Estados", opcion_b:"Isla Grande de Tierra del Fuego", opcion_c:"Isla Hornos", respuesta_correcta:"a"},
  { pregunta:"¿Qué banda argentina cantaba 'Mariposa Tecknicolor'?", categoria:"Cultura General", opcion_a:"Fito Páez", opcion_b:"Soda Stereo", opcion_c:"Los Fabulosos Cadillacs", respuesta_correcta:"a"},
  { pregunta:"¿Quién fue el presidente argentino durante la Guerra de Malvinas?", categoria:"Historia", opcion_a:"Raúl Alfonsín", opcion_b:"Leopoldo Galtieri", opcion_c:"Carlos Menem", respuesta_correcta:"b"},
  { pregunta:"¿Qué ciudad argentina es famosa por su Festival Nacional de Folklore?", categoria:"Cultura General", opcion_a:"Cosquín", opcion_b:"Jesús María", opcion_c:"Bariloche", respuesta_correcta:"a"},
  { pregunta:"¿Qué provincia argentina produce la mayor cantidad de olivares?", categoria:"Geografía", opcion_a:"San Juan", opcion_b:"La Rioja", opcion_c:"Mendoza", respuesta_correcta:"b"},
  { pregunta:"¿Qué jugador argentino es conocido como 'El Kun'?", categoria:"Deportes", opcion_a:"Sergio Agüero", opcion_b:"Kun Agüero", opcion_c:"Ambos son lo mismo", respuesta_correcta:"c"},
  { pregunta:"¿Qué tradición argentina se hace el 29 de cada mes comiendo ñoquis?", categoria:"Cultura General", opcion_a:"Tradición italiana adaptada", opcion_b:"Tradición española", opcion_c:"Tradición indígena", respuesta_correcta:"a"},
  { pregunta:"¿En qué provincia está la Cueva de las Manos?", categoria:"Geografía", opcion_a:"Santa Cruz", opcion_b:"Chubut", opcion_c:"Río Negro", respuesta_correcta:"a"},
  { pregunta:"¿Qué grupo de rock argentino cantaba 'Muchachos, ahora nos volvimos a ilusionar' en su versión Mundial?", categoria:"Cultura General", opcion_a:"La Mosca", opcion_b:"Los Piojos", opcion_c:"Las Pastillas del Abuelo", respuesta_correcta:"a"},
  { pregunta:"¿Qué batalla famosa libró Güemes en el norte argentino?", categoria:"Historia", opcion_a:"Batalla de Salta", opcion_b:"Batalla de Tucumán", opcion_c:"Batalla de Ayacucho", respuesta_correcta:"a"},
  { pregunta:"¿Qué equipo ganó más Copas Libertadores en Argentina?", categoria:"Deportes", opcion_a:"Boca Juniors", opcion_b:"River Plate", opcion_c:"Independiente", respuesta_correcta:"c"},
  { pregunta:"¿Qué bebida típica se toma con bombilla?", categoria:"Cultura General", opcion_a:"Mate", opcion_b:"Tereré", opcion_c:"Ambos", respuesta_correcta:"c"},
  { pregunta:"¿Qué ciudad argentina es conocida como la 'Capital Nacional del Trekking'?", categoria:"Geografía", opcion_a:"El Chaltén", opcion_b:"El Bolsón", opcion_c:"Villa La Angostura", respuesta_correcta:"a"},
  { pregunta:"¿Quién escribió la letra de 'Cambalache'?", categoria:"Cultura General", opcion_a:"Homero Manzi", opcion_b:"Enrique Santos Discépolo", opcion_c:"Celedonio Flores", respuesta_correcta:"b"},
  { pregunta:"¿En qué año Argentina fue campeona olímpica en fútbol por última vez (hasta 2024)?", categoria:"Deportes", opcion_a:"2004", opcion_b:"2008", opcion_c:"2024", respuesta_correcta:"b"},
  { pregunta:"¿Qué provincia argentina limita con Bolivia, Paraguay y Brasil?", categoria:"Geografía", opcion_a:"Formosa", opcion_b:"Misiones", opcion_c:"Salta", respuesta_correcta:"b"},
  { pregunta:"¿Qué actriz argentina ganó un Oscar por 'La historia oficial'?", categoria:"Cultura General", opcion_a:"Norma Aleandro", opcion_b:"Cecilia Roth", opcion_c:"China Zorrilla", respuesta_correcta:"a"},
  { pregunta:"¿Qué apodo tiene el equipo de Racing Club?", categoria:"Deportes", opcion_a:"La Academia", opcion_b:"El Cilindro", opcion_c:"Los Académicos", respuesta_correcta:"a"},
  { pregunta:"¿Qué parque nacional argentino protege al huemul?", categoria:"Geografía", opcion_a:"Los Glaciares", opcion_b:"Nahuel Huapi", opcion_c:"Lanín", respuesta_correcta:"a"},
  { pregunta:"¿Qué cantante argentina es conocida por 'Corazón americano'?", categoria:"Cultura General", opcion_a:"María Elena Walsh", opcion_b:"Mercedes Sosa", opcion_c:"Gilda", respuesta_correcta:"b"},
  { pregunta:"¿En qué año se sancionó la Constitución Argentina actual?", categoria:"Historia", opcion_a:"1853", opcion_b:"1949", opcion_c:"1994", respuesta_correcta:"a"},
  { pregunta:"¿Qué ciudad es la capital de la provincia de Santa Fe?", categoria:"Geografía", opcion_a:"Rosario", opcion_b:"Santa Fe", opcion_c:"Rafaela", respuesta_correcta:"b"},
  { pregunta:"¿Qué banda argentina cantaba 'Los dinosaurios'?", categoria:"Cultura General", opcion_a:"Charly García", opcion_b:"Soda Stereo", opcion_c:"Spinetta Jade", respuesta_correcta:"a"},
  { pregunta:"¿Qué tenista argentino llegó a la final de Wimbledon en 1991?", categoria:"Deportes", opcion_a:"Guillermo Vilas", opcion_b:"David Nalbandian", opcion_c:"Gabriela Sabatini", respuesta_correcta:"c"},
  { pregunta:"¿Qué dulce típico se come en la noche de San Juan en el norte argentino?", categoria:"Cultura General", opcion_a:"Pasteles", opcion_b:"Turrón", opcion_c:"Rosca de Pascua", respuesta_correcta:"a"},
  { pregunta:"¿Qué volcán activo está en la provincia de Neuquén?", categoria:"Geografía", opcion_a:"Lanín", opcion_b:"Copahue", opcion_c:"Domuyo", respuesta_correcta:"b"},
  { pregunta:"¿Quién es el autor de 'Facundo'?", categoria:"Cultura General", opcion_a:"Domingo Faustino Sarmiento", opcion_b:"Esteban Echeverría", opcion_c:"José Mármol", respuesta_correcta:"a"},
  { pregunta:"¿Qué selección argentina ganó el Mundial Sub-20 más veces?", categoria:"Deportes", opcion_a:"6 veces", opcion_b:"5 veces", opcion_c:"4 veces", respuesta_correcta:"a"},
  { pregunta:"¿Qué región argentina es conocida por sus viñedos de altura?", categoria:"Geografía", opcion_a:"Cuyo", opcion_b:"Noroeste", opcion_c:"Patagonia", respuesta_correcta:"b"},
  { pregunta:"¿Qué humorista argentino creó al personaje 'Inodoro Pereyra'?", categoria:"Cultura General", opcion_a:"Quino", opcion_b:"Fontanarrosa", opcion_c:"Caloi", respuesta_correcta:"b"},
  { pregunta:"¿En qué provincia está el Dique Cabra Corral?", categoria:"Geografía", opcion_a:"Jujuy", opcion_b:"Salta", opcion_c:"Tucumán", respuesta_correcta:"b"},
  { pregunta:"¿Qué canción de Charly García dice 'No bombardeen Buenos Aires'?", categoria:"Cultura General", opcion_a:"No voy en tren", opcion_b:"Los dinosaurios", opcion_c:"Inconsciente colectivo", respuesta_correcta:"a"},
  { pregunta:"¿Qué provincia argentina es la más grande en superficie?", categoria:"Geografía", opcion_a:"Santa Cruz", opcion_b:"Buenos Aires", opcion_c:"Chubut", respuesta_correcta:"b"},
{ pregunta:"¿Quién es el autor de la canción 'Sólo se trata de vivir'?", categoria:"Cultura General", opcion_a:"Luis Alberto Spinetta", opcion_b:"Charly García", opcion_c:"León Gieco", respuesta_correcta:"a"},
{ pregunta:"¿Qué equipo de fútbol argentino es conocido como 'El Taladro'?", categoria:"Deportes", opcion_a:"Banfield", opcion_b:"Lanús", opcion_c:"Quilmes", respuesta_correcta:"a"},
{ pregunta:"¿En qué ciudad argentina se encuentra el Obelisco?", categoria:"Geografía", opcion_a:"Rosario", opcion_b:"Buenos Aires", opcion_c:"Córdoba", respuesta_correcta:"b"},
{ pregunta:"¿Qué postre argentino lleva dulce de batata y queso?", categoria:"Cultura General", opcion_a:"Vigilante", opcion_b:"Pastelito", opcion_c:"Quesillo", respuesta_correcta:"a"},
{ pregunta:"¿Qué banda de rock nacional cantaba 'Persiana americana'?", categoria:"Cultura General", opcion_a:"Soda Stereo", opcion_b:"Los Abuelos de la Nada", opcion_c:"Virus", respuesta_correcta:"a"},
{ pregunta:"¿En qué provincia está el Puente del Inca?", categoria:"Geografía", opcion_a:"Mendoza", opcion_b:"San Juan", opcion_c:"Neuquén", respuesta_correcta:"a"},
{ pregunta:"¿Quién fue el presidente argentino que promulgó el voto femenino?", categoria:"Historia", opcion_a:"Juan Domingo Perón", opcion_b:"Hipólito Yrigoyen", opcion_c:"Arturo Illia", respuesta_correcta:"a"},
{ pregunta:"¿Qué jugador argentino ganó la Champions League con el Real Madrid en 2022?", categoria:"Deportes", opcion_a:"Ángel Di María", opcion_b:"Gonzalo Higuaín", opcion_c:"Fernando Redondo", respuesta_correcta:"a"},
{ pregunta:"¿Qué ciudad argentina es conocida como la 'Perla del Norte'?", categoria:"Geografía", opcion_a:"Salta", opcion_b:"San Miguel de Tucumán", opcion_c:"San Salvador de Jujuy", respuesta_correcta:"a"},
{ pregunta:"¿Qué cantante argentina interpretó 'Como la cigarra'?", categoria:"Cultura General", opcion_a:"Mercedes Sosa", opcion_b:"María Elena Walsh", opcion_c:"Susana Rinaldi", respuesta_correcta:"a"},
{ pregunta:"¿Qué equipo de fútbol es el 'Decano' del fútbol argentino?", categoria:"Deportes", opcion_a:"Gimnasia y Esgrima La Plata", opcion_b:"Quilmes", opcion_c:"Olimpo", respuesta_correcta:"a"},
{ pregunta:"¿En qué año se produjo el Cordobazo?", categoria:"Historia", opcion_a:"1969", opcion_b:"1973", opcion_c:"1966", respuesta_correcta:"a"},
{ pregunta:"¿Qué parque nacional argentino alberga al Fitz Roy?", categoria:"Geografía", opcion_a:"Los Glaciares", opcion_b:"Nahuel Huapi", opcion_c:"Perito Moreno", respuesta_correcta:"a"},
{ pregunta:"¿Qué dulce típico se come en Semana Santa en Argentina?", categoria:"Cultura General", opcion_a:"Rosca de Pascua", opcion_b:"Empanadas de vigilia", opcion_c:"Ambas", respuesta_correcta:"c"},
{ pregunta:"¿Qué escritor argentino creó al personaje Don Isidro Parodi?", categoria:"Cultura General", opcion_a:"Jorge Luis Borges", opcion_b:"Adolfo Bioy Casares", opcion_c:"Ambos", respuesta_correcta:"c"},
{ pregunta:"¿Qué provincia argentina es famosa por sus termas?", categoria:"Geografía", opcion_a:"Entre Ríos", opcion_b:"Corrientes", opcion_c:"Ambas", respuesta_correcta:"c"},
{ pregunta:"¿Quién ganó el Dakar 2024 en autos representando a Argentina?", categoria:"Deportes", opcion_a:"Kevin Benavides", opcion_b:"Manuel Andújar", opcion_c:"Ninguno, no hubo argentino", respuesta_correcta:"b"},
{ pregunta:"¿Qué ciudad es la capital de la provincia de La Pampa?", categoria:"Geografía", opcion_a:"Santa Rosa", opcion_b:"General Pico", opcion_c:"Toay", respuesta_correcta:"a"},
{ pregunta:"¿Qué canción de Fito Páez dice '11 y 6'?", categoria:"Cultura General", opcion_a:"Mariposa Tecknicolor", opcion_b:"11 y 6", opcion_c:"Al lado del camino", respuesta_correcta:"b"},
{ pregunta:"¿Qué selección argentina ganó el oro olímpico en básquet en 2004?", categoria:"Deportes", opcion_a:"La Generación Dorada", opcion_b:"Equipo Sub-23", opcion_c:"Ambos", respuesta_correcta:"a"},
{ pregunta:"¿Qué región argentina es conocida como el 'Noroeste' o NOA?", categoria:"Geografía", opcion_a:"Jujuy, Salta, Tucumán, etc.", opcion_b:"Mendoza, San Juan", opcion_c:"Río Negro, Chubut", respuesta_correcta:"a"},
{ pregunta:"¿Qué humorista argentino decía '¡Qué tul?'?", categoria:"Cultura General", opcion_a:"Alberto Olmedo", opcion_b:"Jorge Porcel", opcion_c:"Juan Carlos Altavista", respuesta_correcta:"c"},
{ pregunta:"¿En qué provincia está el Aconcagua?", categoria:"Geografía", opcion_a:"Mendoza", opcion_b:"San Juan", opcion_c:"Neuquén", respuesta_correcta:"a"},
{ pregunta:"¿Qué actriz argentina protagonizó 'El secreto de sus ojos'?", categoria:"Cultura General", opcion_a:"Soledad Villamil", opcion_b:"Ricardo Darín", opcion_c:"Norma Aleandro", respuesta_correcta:"a"},
{ pregunta:"¿Qué equipo de fútbol argentino es conocido como 'El Fortín'?", categoria:"Deportes", opcion_a:"Vélez Sarsfield", opcion_b:"Defensa y Justicia", opcion_c:"Argentinos Juniors", respuesta_correcta:"a"},
{ pregunta:"¿Qué batalla del 25 de mayo de 1810 es conocida como la Revolución de Mayo?", categoria:"Historia", opcion_a:"No fue batalla, fue revolución pacífica", opcion_b:"Batalla de Chacabuco", opcion_c:"Batalla de Suipacha", respuesta_correcta:"a"},
{ pregunta:"¿Qué ciudad argentina es famosa por su carnaval?", categoria:"Cultura General", opcion_a:"Gualeguaychú", opcion_b:"Corrientes", opcion_c:"Ambas", respuesta_correcta:"c"},
{ pregunta:"¿Qué volcán es el más alto del mundo y está en Argentina?", categoria:"Geografía", opcion_a:"Ojos del Salado", opcion_b:"Aconcagua", opcion_c:"Llullaillaco", respuesta_correcta:"a"},
{ pregunta:"¿Qué banda cantaba 'Matador' en los 90?", categoria:"Cultura General", opcion_a:"Los Fabulosos Cadillacs", opcion_b:"Bersuit Vergarabat", opcion_c:"Divididos", respuesta_correcta:"a"},
{ pregunta:"¿En qué año Argentina recuperó la democracia después de la dictadura?", categoria:"Historia", opcion_a:"1983", opcion_b:"1976", opcion_c:"1989", respuesta_correcta:"a"},
{ pregunta:"¿Qué provincia argentina tiene como capital a Rawson?", categoria:"Geografía", opcion_a:"Chubut", opcion_b:"Santa Cruz", opcion_c:"Río Negro", respuesta_correcta:"a"},
{ pregunta:"¿Qué tenista argentino ganó el US Open en 1977?", categoria:"Deportes", opcion_a:"Guillermo Vilas", opcion_b:"José Luis Clerc", opcion_c:"David Nalbandian", respuesta_correcta:"a"},
{ pregunta:"¿Qué comida típica del norte argentino lleva harina de maíz y queso?", categoria:"Cultura General", opcion_a:"Humita", opcion_b:"Locro", opcion_c:"Tamal", respuesta_correcta:"a"},
{ pregunta:"¿Qué escritor argentino es conocido por 'Boquitas pintadas'?", categoria:"Cultura General", opcion_a:"Manuel Puig", opcion_b:"Rodolfo Walsh", opcion_c:"Osvaldo Soriano", respuesta_correcta:"a"},
{ pregunta:"¿Qué equipo ganó el Mundial de Clubes en 2006 representando a Argentina?", categoria:"Deportes", opcion_a:"Boca Juniors", opcion_b:"Estudiantes", opcion_c:"River Plate", respuesta_correcta:"a"},
{ pregunta:"¿En qué provincia está el Tren a las Nubes?", categoria:"Geografía", opcion_a:"Salta", opcion_b:"Jujuy", opcion_c:"Catamarca", respuesta_correcta:"a"},
{ pregunta:"¿Qué cantante de tango es conocido como 'El Zorzal Criollo'?", categoria:"Cultura General", opcion_a:"Carlos Gardel", opcion_b:"Julio Sosa", opcion_c:"Roberto Goyeneche", respuesta_correcta:"a"},
{ pregunta:"¿Qué isla del sur argentino es famosa por sus pingüinos de Magallanes?", categoria:"Geografía", opcion_a:"Isla Martillo", opcion_b:"Isla Pingüino", opcion_c:"Ambas", respuesta_correcta:"c"},
{ pregunta:"¿Qué película argentina ganó el Oscar a Mejor Película Extranjera en 2009?", categoria:"Cultura General", opcion_a:"El secreto de sus ojos", opcion_b:"Relatos salvajes", opcion_c:"El hijo de la novia", respuesta_correcta:"a"},
{ pregunta:"¿Qué apodo tiene Independiente de Avellaneda?", categoria:"Deportes", opcion_a:"El Rey de Copas", opcion_b:"El Diablo Rojo", opcion_c:"Ambos", respuesta_correcta:"c"},
{ pregunta:"¿Qué festividad argentina se celebra el 12 de octubre?", categoria:"Historia", opcion_a:"Día de la Diversidad Cultura Generall Americana", opcion_b:"Día de la Raza", opcion_c:"Antiguo nombre", respuesta_correcta:"a"},
{ pregunta:"¿Qué ciudad es conocida como la 'Ciudad de las Diagonales'?", categoria:"Geografía", opcion_a:"La Plata", opcion_b:"Mar del Plata", opcion_c:"Bahía Blanca", respuesta_correcta:"a"},
{ pregunta:"¿Qué músico argentino creó el personaje Serú Girán?", categoria:"Cultura General", opcion_a:"Charly García", opcion_b:"Luis Alberto Spinetta", opcion_c:"David Lebón", respuesta_correcta:"a"},
{ pregunta:"¿Qué provincia argentina limita con Chile por el Paso de San Francisco?", categoria:"Geografía", opcion_a:"Catamarca", opcion_b:"La Rioja", opcion_c:"Salta", respuesta_correcta:"a"},
{ pregunta:"¿Quién es el máximo goleador histórico de la selección argentina?", categoria:"Deportes", opcion_a:"Lionel Messi", opcion_b:"Gabriel Batistuta", opcion_c:"Diego Maradona", respuesta_correcta:"a"},
{ pregunta:"¿Qué empanada típica lleva aceitunas y huevo duro?", categoria:"Cultura General", opcion_a:"Empanada árabe", opcion_b:"Empanada criolla", opcion_c:"Empanada gallega", respuesta_correcta:"b"},
{ pregunta:"¿En qué año se fundó la Universidad de Córdoba, la más antigua de Argentina?", categoria:"Historia", opcion_a:"1613", opcion_b:"1622", opcion_c:"1871", respuesta_correcta:"a"},
{ pregunta:"¿Qué banda de cumbia argentina es famosa por 'La mano de Dios'?", categoria:"Cultura General", opcion_a:"Rodrigo", opcion_b:"Los Palmeras", opcion_c:"Damas Gratis", respuesta_correcta:"a"},
{ pregunta:"¿Qué lago argentino comparte con Chile y es el más profundo de Sudamérica?", categoria:"Geografía", opcion_a:"Nahuel Huapi", opcion_b:"Argentino", opcion_c:"Viedma", respuesta_correcta:"a"},
{ pregunta:"¿Qué provincia argentina es conocida por sus salinas grandes?", categoria:"Geografía", opcion_a:"Jujuy", opcion_b:"Catamarca", opcion_c:"Salta", respuesta_correcta:"a"},
{ pregunta:"¿Qué banda de rock argentina cantaba 'Spaghetti del rock'?", categoria:"Cultura General", opcion_a:"Divididos", opcion_b:"Los Piojos", opcion_c:"Patricio Rey y sus Redonditos de Ricota", respuesta_correcta:"a"},
{ pregunta:"¿Qué equipo de fútbol argentino es conocido como 'El Tiburón'?", categoria:"Deportes", opcion_a:"Aldosivi", opcion_b:"Argentino de Quilmes", opcion_c:"Platense", respuesta_correcta:"a"},
{ pregunta:"¿Qué ciudad argentina es famosa por el Festival de Tango?", categoria:"Cultura General", opcion_a:"Buenos Aires", opcion_b:"Medellín", opcion_c:"La Plata", respuesta_correcta:"a"},
{ pregunta:"¿En qué provincia está el Bosque Petrificado?", categoria:"Geografía", opcion_a:"Santa Cruz", opcion_b:"Chubut", opcion_c:"Río Negro", respuesta_correcta:"a"},
{ pregunta:"¿Qué cantante de tango era conocido como 'El Polaco'?", categoria:"Cultura General", opcion_a:"Roberto Goyeneche", opcion_b:"Edmundo Rivero", opcion_c:"Julio Sosa", respuesta_correcta:"c"},
{ pregunta:"¿Qué selección argentina ganó el Mundial de Futsal en 2016?", categoria:"Deportes", opcion_a:"No ganó", opcion_b:"Sí, en 2016", opcion_c:"En 2024", respuesta_correcta:"b"},
{ pregunta:"¿Qué escritor argentino publicó 'Sobre héroes y tumbas'?", categoria:"Cultura General", opcion_a:"Ernesto Sabato", opcion_b:"Julio Cortázar", opcion_c:"Jorge Luis Borges", respuesta_correcta:"a"},
{ pregunta:"¿Qué río argentino es el más caudaloso?", categoria:"Geografía", opcion_a:"Paraná", opcion_b:"Río de la Plata", opcion_c:"Colorado", respuesta_correcta:"a"},
{ pregunta:"¿Qué tradición argentina implica brindar con sidra en Navidad y Año Nuevo?", categoria:"Cultura General", opcion_a:"Tradición familiar típica", opcion_b:"Solo en el norte", opcion_c:"Solo en Patagonia", respuesta_correcta:"a"},
{ pregunta:"¿Qué jugador argentino es conocido como 'El Principito'?", categoria:"Deportes", opcion_a:"Enzo Fernández", opcion_b:"Ángel Correa", opcion_c:"Giovani Lo Celso", respuesta_correcta:"a"},
{ pregunta:"¿En qué provincia se encuentra el Valle Calchaquí?", categoria:"Geografía", opcion_a:"Salta", opcion_b:"Tucumán", opcion_c:"Catamarca", respuesta_correcta:"a"},
{ pregunta:"¿Qué película argentina tiene a Ricardo Darín como 'El Clan'?", categoria:"Cultura General", opcion_a:"El Clan", opcion_b:"Relatos salvajes", opcion_c:"Nueve reinas", respuesta_correcta:"a"},
{ pregunta:"¿Qué equipo de fútbol es el 'Lobo' de La Plata?", categoria:"Deportes", opcion_a:"Gimnasia y Esgrima", opcion_b:"Estudiantes", opcion_c:"Platense", respuesta_correcta:"a"},
{ pregunta:"¿Qué ciudad argentina es conocida como la 'Capital Nacional de la Manzana'?", categoria:"Geografía", opcion_a:"General Roca", opcion_b:"Neuquén", opcion_c:"Cipolletti", respuesta_correcta:"a"},
{ pregunta:"¿Qué canción de León Gieco dice 'Solo le pido a Dios'?", categoria:"Cultura General", opcion_a:"Solo le pido a Dios", opcion_b:"En el país de la libertad", opcion_c:"La memoria", respuesta_correcta:"a"},
{ pregunta:"¿En qué año se produjo el regreso de Perón a Argentina después del exilio?", categoria:"Historia", opcion_a:"1973", opcion_b:"1972", opcion_c:"1976", respuesta_correcta:"a"},
{ pregunta:"¿Qué provincia argentina tiene como capital a Viedma?", categoria:"Geografía", opcion_a:"Río Negro", opcion_b:"Chubut", opcion_c:"Neuquén", respuesta_correcta:"a"},
{ pregunta:"¿Qué bebida típica del litoral argentino es el tereré?", categoria:"Cultura General", opcion_a:"Sí, en verano", opcion_b:"Solo mate caliente", opcion_c:"Solo en Paraguay", respuesta_correcta:"a"},
{ pregunta:"¿Qué basquetbolista argentino jugó más tiempo en la NBA?", categoria:"Deportes", opcion_a:"Manu Ginóbili", opcion_b:"Luis Scola", opcion_c:"Andrés Nocioni", respuesta_correcta:"a"},
{ pregunta:"¿Qué parque nacional protege la Península Valdés?", categoria:"Geografía", opcion_a:"Península Valdés", opcion_b:"Los Glaciares", opcion_c:"Iguazú", respuesta_correcta:"a"},
{ pregunta:"¿Qué humorista argentino creó 'Mafalda'?", categoria:"Cultura General", opcion_a:"Quino", opcion_b:"Fontanarrosa", opcion_c:"Landrú", respuesta_correcta:"a"},
{ pregunta:"¿Qué ciudad es la capital de Tierra del Fuego?", categoria:"Geografía", opcion_a:"Ushuaia", opcion_b:"Río Grande", opcion_c:"Tolhuin", respuesta_correcta:"a"},
{ pregunta:"¿Qué banda argentina cantaba 'Devuélveme a mi chica'?", categoria:"Cultura General", opcion_a:"Hombres G", opcion_b:"Virus", opcion_c:"Soda Stereo", respuesta_correcta:"a"},
{ pregunta:"¿En qué año Argentina ganó su tercera Copa del Mundo?", categoria:"Deportes", opcion_a:"2022", opcion_b:"2026", opcion_c:"2014", respuesta_correcta:"a"},
{ pregunta:"¿Qué dulce típico argentino lleva cayote?", categoria:"Cultura General", opcion_a:"Dulce de cayote", opcion_b:"Dulce de membrillo", opcion_c:"Dulce de alcayota", respuesta_correcta:"c"},
{ pregunta:"¿Qué escritor argentino es conocido por 'Operación Masacre'?", categoria:"Cultura General", opcion_a:"Rodolfo Walsh", opcion_b:"Osvaldo Soriano", opcion_c:"Tomás Eloy Martínez", respuesta_correcta:"a"},
{ pregunta:"¿Qué provincia argentina es la menos poblada?", categoria:"Geografía", opcion_a:"Santa Cruz", opcion_b:"Tierra del Fuego", opcion_c:"Santa Cruz", respuesta_correcta:"b"},
{ pregunta:"¿Qué canción de Los Abuelos de la Nada dice 'Mil horas'?", categoria:"Cultura General", opcion_a:"Mil horas", opcion_b:"Costumbres argentinas", opcion_c:"Sin gamulán", respuesta_correcta:"a"},
{ pregunta:"¿Qué tenista argentina ganó Wimbledon en dobles mixtos?", categoria:"Deportes", opcion_a:"Gabriela Sabatini", opcion_b:"Paola Suárez", opcion_c:"Gisela Dulko", respuesta_correcta:"b"},
{ pregunta:"¿Cuál es la capital de la provincia de Chaco?", categoria:"Geografía", opcion_a:"Resistencia", opcion_b:"Sáenz Peña", opcion_c:"Corrientes", respuesta_correcta:"a"},
{ pregunta:"¿Qué banda de rock nacional lanzó el álbum 'Artaud'?", categoria:"Cultura General", opcion_a:"Pescado Rabioso", opcion_b:"Sui Generis", opcion_c:"Manal", respuesta_correcta:"a"},
{ pregunta:"¿Qué equipo de básquet argentino es el más ganador de la Liga Nacional?", categoria:"Deportes", opcion_a:"Peñarol de Mar del Plata", opcion_b:"Atenas de Córdoba", opcion_c:"San Lorenzo", respuesta_correcta:"b"},
{ pregunta:"¿En qué año se creó la bandera argentina?", categoria:"Historia", opcion_a:"1812", opcion_b:"1816", opcion_c:"1818", respuesta_correcta:"a"},
{ pregunta:"¿Qué postre típico argentino lleva chocolate, dulce de leche y merengue italiano?", categoria:"Cultura General", opcion_a:"Chocotorta", opcion_b:"Rogell", opcion_c:"Torta Balcarce", respuesta_correcta:"b"},
{ pregunta:"¿Qué provincia argentina es famosa por la producción de té?", categoria:"Geografía", opcion_a:"Misiones", opcion_b:"Corrientes", opcion_c:"Entre Ríos", respuesta_correcta:"a"},
{ pregunta:"¿Quién es el máximo ganador histórico de la Fórmula 1 argentina (TC)?", categoria:"Deportes", opcion_a:"Juan María Traverso", opcion_b:"Guillermo Ortelli", opcion_c:"Matías Rossi", respuesta_correcta:"b"},
{ pregunta:"¿Qué escritor argentino escribió 'Ficciones'?", categoria:"Cultura General", opcion_a:"Jorge Luis Borges", opcion_b:"Julio Cortázar", opcion_c:"Ernesto Sabato", respuesta_correcta:"a"},
{ pregunta:"¿En qué provincia se encuentra el Parque Nacional El Leoncito?", categoria:"Geografía", opcion_a:"San Juan", opcion_b:"La Rioja", opcion_c:"Mendoza", respuesta_correcta:"a"},
{ pregunta:"¿Qué cantante argentina ganó el Grammy Latino a Mejor Álbum Folklórico varias veces?", categoria:"Cultura General", opcion_a:"Mercedes Sosa", opcion_b:"Soledad Pastorutti", opcion_c:"Atahualpa Yupanqui", respuesta_correcta:"b"},
{ pregunta:"¿Qué selección argentina ganó el Mundial de Hockey sobre césped femenino en 2002 y 2010?", categoria:"Deportes", opcion_a:"Las Leonas", opcion_b:"Los Leones", opcion_c:"Las Kamikaze", respuesta_correcta:"a"},
{ pregunta:"¿Quién diseñó la bandera argentina?", categoria:"Historia", opcion_a:"Manuel Belgrano", opcion_b:"San Martín", opcion_c:"Juan José Castelli", respuesta_correcta:"a"},
{ pregunta:"¿Qué ciudad argentina es conocida como la 'Capital del Trigo'?", categoria:"Geografía", opcion_a:"Pergamino", opcion_b:"Tres Arroyos", opcion_c:"Venado Tuerto", respuesta_correcta:"a"},
{ pregunta:"¿Qué dúo de humoristas argentinos eran 'Cha Cha Cha'?", categoria:"Cultura General", opcion_a:"Alfredo Casero, Fabio Alberti y Diego Capusotto", opcion_b:"Olmedo y Porcel", opcion_c:"Midachi", respuesta_correcta:"a"},
{ pregunta:"¿Qué piloto argentino ganó el Rally Dakar en motos más veces?", categoria:"Deportes", opcion_a:"Kevin Benavides", opcion_b:"Marcos Patronelli", opcion_c:"Orlando Terranova", respuesta_correcta:"a"},
{ pregunta:"¿En qué año se firmó el Tratado del Pilar?", categoria:"Historia", opcion_a:"1819", opcion_b:"1820", opcion_c:"1826", respuesta_correcta:"b"},
{ pregunta:"¿Qué provincia argentina tiene como capital a Paraná?", categoria:"Geografía", opcion_a:"Entre Ríos", opcion_b:"Corrientes", opcion_c:"Santa Fe", respuesta_correcta:"a"},
{ pregunta:"¿Qué serie argentina de TV es famosa por 'Esperando la carroza'?", categoria:"Cultura General", opcion_a:"Película, no serie", opcion_b:"Los Campanelli", opcion_c:"Son de Diez", respuesta_correcta:"a"},
{ pregunta:"¿Qué voleibolista argentino es considerado uno de los mejores del mundo?", categoria:"Deportes", opcion_a:"Facundo Conte", opcion_b:"Luciano De Cecco", opcion_c:"Javier Weber", respuesta_correcta:"b"},
{ pregunta:"¿Qué himno nacional argentino fue compuesto por Blas Parera?", categoria:"Historia", opcion_a:"Música", opcion_b:"Letra por Vicente López y Planes", opcion_c:"Ambos", respuesta_correcta:"a"},
{ pregunta:"¿Qué cascada argentina es más alta que las del Iguazú individualmente?", categoria:"Geografía", opcion_a:"Ninguna", opcion_b:"Salto del Agrio", opcion_c:"No hay", respuesta_correcta:"a"},
{ pregunta:"¿Qué cantante de cumbia villera es conocido como 'El Comandante'?", categoria:"Cultura General", opcion_a:"Damas Gratis - Pablo Lescano", opcion_b:"Yerba Brava", opcion_c:"Néstor en Bloque", respuesta_correcta:"a"},
{ pregunta:"¿Qué rugbier argentino es capitán histórico de Los Pumas?", categoria:"Deportes", opcion_a:"Agustín Creevy", opcion_b:"Pablo Matera", opcion_c:"Felipe Contepomi", respuesta_correcta:"a"},
{ pregunta:"¿En qué batalla San Martín derrotó a los realistas en Chile?", categoria:"Historia", opcion_a:"Chacabuco", opcion_b:"Maipú", opcion_c:"Cancha Rayada", respuesta_correcta:"a"},
{ pregunta:"¿Qué ciudad argentina es sede del Festival de Jesús María?", categoria:"Cultura General", opcion_a:"Jesús María", opcion_b:"Cosquín", opcion_c:"Villa María", respuesta_correcta:"a"},
{ pregunta:"¿Qué provincia argentina produce más yerba mate?", categoria:"Geografía", opcion_a:"Misiones", opcion_b:"Corrientes", opcion_c:"Ambas", respuesta_correcta:"a"},
{ pregunta:"¿Qué boxeador argentino es conocido como 'El Macho' Camacho? Espera, argentino: Carlos Monzón o Pascual Pérez?", categoria:"Deportes", opcion_a:"Carlos Monzón", opcion_b:"Pascual Pérez", opcion_c:"Luis Ángel Firpo", respuesta_correcta:"a"},
{ pregunta:"¿Qué poeta argentino escribió 'Luna de enfrente'?", categoria:"Cultura General", opcion_a:"Jorge Luis Borges", opcion_b:"Alfonsina Storni", opcion_c:"Leopoldo Lugones", respuesta_correcta:"a"},
{ pregunta:"¿Qué isla argentina reclama el Reino Unido como Malvinas?", categoria:"Historia", opcion_a:"Islas Malvinas", opcion_b:"Georgias del Sur", opcion_c:"Sandwich del Sur", respuesta_correcta:"a"},
{ pregunta:"¿Qué parque nacional argentino tiene los Arrayanes?", categoria:"Geografía", opcion_a:"Los Arrayanes", opcion_b:"Nahuel Huapi", opcion_c:"Lanín", respuesta_correcta:"a"},
{ pregunta:"¿Qué comediante argentino hacía 'No hay 2 sin 3'?", categoria:"Cultura General", opcion_a:"Jorge Guinzburg", opcion_b:"Antonio Gasalla", opcion_c:"Juan Verdaguer", respuesta_correcta:"a"},
{ pregunta:"¿Qué golfista argentino ganó el Masters de Augusta?", categoria:"Deportes", opcion_a:"Ángel Cabrera", opcion_b:"Eduardo Romero", opcion_c:"Roberto De Vicenzo", respuesta_correcta:"a"},
{ pregunta:"¿En qué año se creó la CONADEP para investigar desaparecidos?", categoria:"Historia", opcion_a:"1983", opcion_b:"1984", opcion_c:"1976", respuesta_correcta:"b"},
{ pregunta:"¿Qué ciudad es conocida como la 'Ciudad Jardín' en Buenos Aires?", categoria:"Geografía", opcion_a:"Palermo", opcion_b:"Lomas de Zamora", opcion_c:"Vicente López", respuesta_correcta:"a"},
{ pregunta:"¿Qué grupo de folklore argentino es 'Los Nocheros' de?", categoria:"Cultura General", opcion_a:"Salta", opcion_b:"Anta", opcion_c:"Jujuy", respuesta_correcta:"b"},
{ pregunta:"¿Qué nadadora argentina ganó medalla en los Juegos Panamericanos?", categoria:"Deportes", opcion_a:"Delfina Pignatiello", opcion_b:"Virginia Bardach", opcion_c:"Georgina Bardach", respuesta_correcta:"c"},
{ pregunta:"¿Quién fue la primera mujer presidenta de Argentina?", categoria:"Historia", opcion_a:"Cristina Fernández", opcion_b:"Isabel Perón", opcion_c:"Eva Perón", respuesta_correcta:"b"},
{ pregunta:"¿Qué desierto está en el noroeste argentino?", categoria:"Geografía", opcion_a:"Puna", opcion_b:"Monte", opcion_c:"Patagónico", respuesta_correcta:"a"},
{ pregunta:"¿Qué programa de TV argentino tenía a Marcelo Tinelli en sus inicios?", categoria:"Cultura General", opcion_a:"Videomatch", opcion_b:"Showmatch", opcion_c:"Ritmo de la noche", respuesta_correcta:"a"},
{ pregunta:"¿Qué ciclista argentino ganó etapas en el Tour de France?", categoria:"Deportes", opcion_a:"Juan Antonio Flecha", opcion_b:"Maximiliano Richeze", opcion_c:"Ninguno famoso", respuesta_correcta:"b"},
{ pregunta:"¿En qué año se aprobó el divorcio vincular en Argentina?", categoria:"Historia", opcion_a:"1987", opcion_b:"1976", opcion_c:"1995", respuesta_correcta:"a"},
{ pregunta:"¿Qué provincia tiene la Fiesta Nacional del Poncho?", categoria:"Cultura General", opcion_a:"Catamarca", opcion_b:"La Rioja", opcion_c:"Santiago del Estero", respuesta_correcta:"a"},
{ pregunta:"¿Qué programa argentino de los 80 tenía a Juan Carlos Mesa y Gianni Lunadei como protagonistas en una pensión?", categoria:"Cultura General", opcion_a:"Mesa de noticias", opcion_b:"Son de Diez", opcion_c:"Los Campanelli", respuesta_correcta:"b"},
{ pregunta:"¿Cómo se llamaba el personaje de Alberto Olmedo en 'No toca botón'?", categoria:"Cultura General", opcion_a:"El manosanta", opcion_b:"Rucucu", opcion_c:"El capitán Piluso", respuesta_correcta:"a"},
{ pregunta:"¿Qué programa conducido por Marcelo Tinelli empezó como 'Videomatch' y luego se convirtió en 'Showmatch'?", categoria:"Cultura General", opcion_a:"Videomatch", opcion_b:"Ritmo de la noche", opcion_c:"Badía y Cía", respuesta_correcta:"a"},
{ pregunta:"¿En qué novela argentina de los 90 actuaban Pablo Echarri y Nancy Dupláa como 'Los Busca'?", categoria:"Cultura General", opcion_a:"Los buscas de siempre", opcion_b:"Por siempre mujercitas", opcion_c:"Montaña rusa", respuesta_correcta:"a"},
{ pregunta:"¿Qué ciclo infantil presentaba 'La revista de Cris Morena' con el personaje de Xuxa en Argentina?", categoria:"Cultura General", opcion_a:"Festilindo", opcion_b:"Jugate conmigo", opcion_c:"El show de Xuxa", respuesta_correcta:"c"},
{ pregunta:"¿Cómo se llamaba el programa de chimentos de Jorge Rial en los 2000?", categoria:"Cultura General", opcion_a:"Intrusos en el espectáculo", opcion_b:"Paparazzi", opcion_c:"Indiscreciones", respuesta_correcta:"a"},
{ pregunta:"¿Qué telecomedia argentina tenía a Guillermo Francella como un psicólogo torpe?", categoria:"Cultura General", opcion_a:"Poné a Francella", opcion_b:"La familia Benvenuto", opcion_c:"Naranja y media", respuesta_correcta:"a"},
{ pregunta:"¿En qué año se emitió por primera vez 'Grande Pa!' con Arturo Puig?", categoria:"Cultura General", opcion_a:"1991", opcion_b:"1995", opcion_c:"1988", respuesta_correcta:"a"},
{ pregunta:"¿Qué programa de Susana Giménez incluía el famoso 'Avión' para regalar premios?", categoria:"Cultura General", opcion_a:"Hola Susana", opcion_b:"Susana Giménez", opcion_c:"Susana quiere", respuesta_correcta:"b"},
{ pregunta:"¿Cómo se llamaba la tira juvenil de Cris Morena con Camila Bordonaba y Benjamín Rojas en 'Rebelde Way'?", categoria:"Cultura General", opcion_a:"Erreway", opcion_b:"Chiquititas", opcion_c:"Floricienta", respuesta_correcta:"a"},
{ pregunta:"¿Qué conductor famoso tenía el programa 'Fax' en los 90?", categoria:"Cultura General", opcion_a:"Nicolás Repetto", opcion_b:"Marcelo Tinelli", opcion_c:"Juan Alberto Badía", respuesta_correcta:"a"},
{ pregunta:"¿En qué novela de Pol-ka actuaban Natalia Oreiro y Facundo Arana como Milagros y Ivo?", categoria:"Cultura General", opcion_a:"Muñeca brava", opcion_b:"Son de fieras", opcion_c:"Gasoleros", respuesta_correcta:"a"},
{ pregunta:"¿Qué programa de Moria Casán era famoso por sus 'mesazas'?", categoria:"Cultura General", opcion_a:"Almorzando con Moria Casán", opcion_b:"La noche de Moria", opcion_c:"Intrusos", respuesta_correcta:"a"},
{ pregunta:"¿Cómo se llamaba el personaje de Antonio Gasalla que era una empleada doméstica?", categoria:"Cultura General", opcion_a:"La emple 99", opcion_b:"La nona", opcion_c:"La abuela", respuesta_correcta:"a"},
{ pregunta:"¿Qué reality show argentino de canto lanzó a artistas como Lali Espósito?", categoria:"Cultura General", opcion_a:"Cantando por un sueño", opcion_b:"Operación Triunfo", opcion_c:"Latin American Idol", respuesta_correcta:"a"},
{ pregunta:"¿En qué programa de los 70 actuaba Olmedo como el dictador Rogelio Moretto?", categoria:"Cultura General", opcion_a:"No toca botón", opcion_b:"Alberto y el dictador", opcion_c:"El chupete", respuesta_correcta:"a"},
{ pregunta:"¿Qué tira de los 2000 tenía a Pablo Rago y Julieta Díaz como 'Los pensionados'?", categoria:"Cultura General", opcion_a:"Son amores", opcion_b:"Los Roldán", opcion_c:"Durmiendo con mi jefe", respuesta_correcta:"b"},
{ pregunta:"¿Qué conductor tenía el programa 'Sábado Bus'?", categoria:"Cultura General", opcion_a:"Nicolás Repetto", opcion_b:"Horacio Embón", opcion_c:"Leo Rosenwasser", respuesta_correcta:"a"},
{ pregunta:"¿En qué novela actuaban Arnaldo André y Luisa Kuliok como amantes prohibidos?", categoria:"Cultura General", opcion_a:"Amo y señor", opcion_b:"Ella y él", opcion_c:"Antonella", respuesta_correcta:"a"},
{ pregunta:"¿Qué programa de Guido Kaczka es famoso por 'El último pasajero'?", categoria:"Cultura General", opcion_a:"A todo o nada", opcion_b:"El último pasajero", opcion_c:"Los 8 escalones", respuesta_correcta:"b"},
{ pregunta:"¿Cómo se llamaba el ciclo de Tinelli con competencias de baile?", categoria:"Cultura General", opcion_a:"Patito sobre hielo", opcion_b:"Bailando por un sueño", opcion_c:"Cantando por un sueño", respuesta_correcta:"b"},
{ pregunta:"¿Qué actriz protagonizó 'Nano' como una niñera robot?", categoria:"Cultura General", opcion_a:"Araceli González", opcion_b:"Natalia Oreiro", opcion_c:"Romina Yan", respuesta_correcta:"a"},
{ pregunta:"¿Qué programa de Lino Patalano y Carmen Barbieri era 'Inconquistable'?", categoria:"Cultura General", opcion_a:"La revista de Carmen", opcion_b:"Incomparables", opcion_c:"Inconquistable corazón", respuesta_correcta:"c"},
{ pregunta:"¿En qué año se estrenó 'Chiquititas' de Cris Morena?", categoria:"Cultura General", opcion_a:"1995", opcion_b:"1998", opcion_c:"2001", respuesta_correcta:"a"},
{ pregunta:"¿Qué conductor famoso tenía 'Imagen de la vida' en los 90?", categoria:"Cultura General", opcion_a:"Nicolás Repetto", opcion_b:"Juan Alberto Badía", opcion_c:"Fernando Bravo", respuesta_correcta:"a"},
{ pregunta:"¿Qué tira tenía a Florencia Peña como Monita en un gimnasio de box?", categoria:"Cultura General", opcion_a:"Casados con hijos", opcion_b:"Son de fieras", opcion_c:"Disputas", respuesta_correcta:"a"},
{ pregunta:"¿Qué reality de Gran Hermano tuvo su primera edición argentina en 2001?", categoria:"Cultura General", opcion_a:"2001", opcion_b:"2007", opcion_c:"2011", respuesta_correcta:"a"},
{ pregunta:"¿Qué programa de Susana Giménez tenía el segmento 'Hola Susana, te quiero hablar'?", categoria:"Cultura General", opcion_a:"Hola Susana", opcion_b:"Susana Giménez", opcion_c:"Susana quiere más", respuesta_correcta:"a"},
{ pregunta:"¿En qué novela de los 80 actuaba Grecia Colmenares como Rosalía?", categoria:"Cultura General", opcion_a:"Topacio", opcion_b:"María de nadie", opcion_c:"Una voz en el teléfono", respuesta_correcta:"b"},
{ pregunta:"¿Qué ciclo de Marcelo Tinelli incluyó 'Patito Feo' en su productora?", categoria:"Cultura General", opcion_a:"Ideas del Sur", opcion_b:"Patito sobre hielo", opcion_c:"No es directo", respuesta_correcta:"a"},
{ pregunta:"¿Qué pareja famosa de los 2000 se conoció en la novela 'Muñeca Brava' y luego se separó escandalosamente?", categoria:"Entretenimiento", opcion_a:"Natalia Oreiro y Facundo Arana", opcion_b:"Romina Yan y Guido Kaczka", opcion_c:"Millie Stegman y Pablo Echarri", respuesta_correcta:"a"},
{ pregunta:"¿Quién fue la participante de Gran Hermano que salió con Marcelo Tinelli después de ganar fama en el reality?", categoria:"Entretenimiento", opcion_a:"Gastón Trezeguet", opcion_b:"Silvina Luna", opcion_c:"Mariela Montero", respuesta_correcta:"b"},
{ pregunta:"¿Qué modelo argentina tuvo un mediático romance con Luis Ortega y luego con Benjamín Vicuña?", categoria:"Entretenimiento", opcion_a:"Pampita", opcion_b:"Luisana Lopilato", opcion_c:"Nicole Neumann", respuesta_correcta:"a"},
{ pregunta:"¿En qué año explotó el escándalo de Wanda Nara y Mauro Icardi con Maxi López?", categoria:"Entretenimiento", opcion_a:"2013", opcion_b:"2015", opcion_c:"2011", respuesta_correcta:"a"},
{ pregunta:"¿Qué actriz fue acusada de ser la tercera en discordia entre Pampita y Benjamín Vicuña en el 'Motorhomegate'?", categoria:"Entretenimiento", opcion_a:"Paula Chaves", opcion_b:"Laurita Fernández", opcion_c:"Eugenia 'China' Suárez", respuesta_correcta:"c"},
{ pregunta:"¿Quién era la pareja de Ricardo Fort cuando irrumpió en la farándula en 2009?", categoria:"Entretenimiento", opcion_a:"Rodrigo Díaz", opcion_b:"Ernesto Ezequiel", opcion_c:"Ninguna, era soltero", respuesta_correcta:"a"},
{ pregunta:"¿Qué cantante argentina tuvo un romance muy publicitado con Diego Maradona en los 2010?", categoria:"Entretenimiento", opcion_a:"Karina La Princesita", opcion_b:"Verónica Ojeda", opcion_c:"Rocío Oliva", respuesta_correcta:"c"},
{ pregunta:"¿En qué reality de baile se conoció la pareja Zaira Nara y Jakob von Plessen?", categoria:"Entretenimiento", opcion_a:"Bailando por un Sueño", opcion_b:"Cantando por un Sueño", opcion_c:"Patinando por un Sueño", respuesta_correcta:"a"},
{ pregunta:"¿Qué modelo tuvo un sonado juicio con Matías Alé por violencia de género en los 2000?", categoria:"Entretenimiento", opcion_a:"Silvina Luna", opcion_b:"Graciela Alfano", opcion_c:"Tiane Grau", respuesta_correcta:"a"},
{ pregunta:"¿Qué futbolista dejó a su esposa por Nicole Neumann en los 2000?", categoria:"Entretenimiento", opcion_a:"Fabio Cannavaro", opcion_b:"Mario Santana", opcion_c:"Gonzalo Bergessio", respuesta_correcta:"b"},
{ pregunta:"¿En qué año Pampita y Benjamín Vicuña anunciaron su separación tras el 'Motorhomegate'?", categoria:"Entretenimiento", opcion_a:"2012", opcion_b:"2015", opcion_c:"2008", respuesta_correcta:"a"},
{ pregunta:"¿En qué año explotó el 'Wandagate' con Wanda Nara, China Suárez y Mauro Icardi?", categoria:"Entretenimiento", opcion_a:"2021", opcion_b:"2019", opcion_c:"2023", respuesta_correcta:"a"},
{ pregunta:"¿Qué modelo argentina fue novia de Juan Mónaco antes de Pampita?", categoria:"Entretenimiento", opcion_a:"Luisana Lopilato", opcion_b:"Zaira Nara", opcion_c:"Carolina Baldini", respuesta_correcta:"a"},
{ pregunta:"¿Quién fue la supuesta tercera en discordia entre Paula Chaves y Pedro Alfonso?", categoria:"Entretenimiento", opcion_a:"Laurita Fernández", opcion_b:"Noelia Marzol", opcion_c:"Flor Vigna", respuesta_correcta:"b"},
{ pregunta:"¿Qué cantante de cumbia tuvo un hijo con Romina de Gran Hermano?", categoria:"Entretenimiento", opcion_a:"Leo Mattioli", opcion_b:"Damian Córdoba", opcion_c:"Néstor en Bloque", respuesta_correcta:"b"},
{ pregunta:"¿En qué reality se conoció la pareja Barby Silenzi y El Polaco?", categoria:"Entretenimiento", opcion_a:"Bailando por un Sueño", opcion_b:"Cantando por un Sueño", opcion_c:"Gran Hermano", respuesta_correcta:"a"},
{ pregunta:"¿Quién era la pareja de Benjamín Vicuña cuando se lo vinculó con China Suárez en el 'Motorhomegate'?", categoria:"Entretenimiento", opcion_a:"Pampita", opcion_b:"Valeria Mazza", opcion_c:"Luciana Salazar", respuesta_correcta:"a"},
{ pregunta:"¿En qué año Nicole Neumann y Fabián Cubero anunciaron su separación?", categoria:"Entretenimiento", opcion_a:"2017", opcion_b:"2020", opcion_c:"2015", respuesta_correcta:"a"},
{ pregunta:"¿Qué futbolista tuvo un romance con Luciana Salazar en los 2000?", categoria:"Entretenimiento", opcion_a:"Martín Palermo", opcion_b:"Juan Sebastián Verón", opcion_c:"Diego Simeone", respuesta_correcta:"a"},
{ pregunta:"¿Qué pareja famosa se separó tras el escándalo de fotos en Badoo?", categoria:"Entretenimiento", opcion_a:"Graciela Alfano y Leandro Penna", opcion_b:"Rodrigo Bueno y su novia", opcion_c:"Matías Tasín y Evelyn Scheidl", respuesta_correcta:"a"},
{ pregunta:"¿Quién fue la novia de Benjamín Rojas después de María Del Cerro?", categoria:"Entretenimiento", opcion_a:"Candela Vetrano", opcion_b:"Eugenia Suárez", opcion_c:"Lali Espósito", respuesta_correcta:"a"},
{ pregunta:"¿Qué modelo tuvo un hijo con Marcelo Gallardo en secreto durante años?", categoria:"Entretenimiento", opcion_a:"Geraldine La Rosa", opcion_b:"Alina Moine", opcion_c:"Soledad Fandiño", respuesta_correcta:"b"},
{ pregunta:"¿En qué año Lali Espósito y Mariano Martínez terminaron su relación?", categoria:"Entretenimiento", opcion_a:"2016", opcion_b:"2018", opcion_c:"2014", respuesta_correcta:"a"},
{ pregunta:"¿Qué panelista de LAM es famosa por sus peleas mediáticas con Yanina Latorre?", categoria:"Entretenimiento", opcion_a:"Ángel de Brito", opcion_b:"Marixa Bali", opcion_c:"Andrea Taboada", respuesta_correcta:"b"},
{ pregunta:"¿Qué actriz de Rebelde Way salió con Peter Alfonso antes que Paula Chaves?", categoria:"Entretenimiento", opcion_a:"Florencia Bertotti", opcion_b:"Luisana Lopilato", opcion_c:"Noelia Marzol", respuesta_correcta:"a"},
{ pregunta:"¿Quién fue el novio de Florencia Peña que generó escándalo por infidelidad con una participante del Bailando?", categoria:"Entretenimiento", opcion_a:"Marcelo Tinelli", opcion_b:"Ramiro Ponce de León", opcion_c:"Guido Kaczka", respuesta_correcta:"b"},
{ pregunta:"¿Qué pareja mediática se formó en el Bailando 2014 entre Noelia Pompa y un futbolista?", categoria:"Entretenimiento", opcion_a:"Hernán Piquín", opcion_b:"Facundo González", opcion_c:"Jorge Moliniers", respuesta_correcta:"a"},
{ pregunta:"¿Qué modelo argentina estuvo en pareja con Tenista Juan Martín del Potro?", categoria:"Entretenimiento", opcion_a:"Camila Holmes", opcion_b:"Julia Rohden", opcion_c:"Ambas", respuesta_correcta:"c"},
{ pregunta:"¿En qué año se separó Laurita Fernández de Nicolás Cabré?", categoria:"Entretenimiento", opcion_a:"2018", opcion_b:"2020", opcion_c:"2016", respuesta_correcta:"a"},
{ pregunta:"¿Qué cantante tuvo un romance con Yanina Screpante antes que con Wanda Nara?", categoria:"Entretenimiento", opcion_a:"Mauro Icardi", opcion_b:"Paulo Dybala", opcion_c:"Sergio Agüero", respuesta_correcta:"a"}
];
