const PREGUNTAS = [

/* =======================
   CULTURA GENERAL
======================= */
{
  pregunta: "¿Cuál es la moneda oficial de Argentina?",
  categoria: "Cultura General",
  opcion_a: "Peso",
  opcion_b: "Dólar",
  opcion_c: "Real",
  respuesta_correcta: "a"
},
{
  pregunta: "¿Cuántos colores tiene la bandera argentina?",
  categoria: "Cultura General",
  opcion_a: "Dos",
  opcion_b: "Tres",
  opcion_c: "Cuatro",
  respuesta_correcta: "b"
},
{
  pregunta: "¿Qué día se celebra el Día de la Independencia en Argentina?",
  categoria: "Cultura General",
  opcion_a: "25 de mayo",
  opcion_b: "9 de julio",
  opcion_c: "20 de junio",
  respuesta_correcta: "b"
},
{
  pregunta: "¿Cuál es el idioma oficial de Argentina?",
  categoria: "Cultura General",
  opcion_a: "Portugués",
  opcion_b: "Español",
  opcion_c: "Italiano",
  respuesta_correcta: "b"
},

/* =======================
   HISTORIA
======================= */
{
  pregunta: "¿En qué año fue la Revolución de Mayo?",
  categoria: "Historia",
  opcion_a: "1810",
  opcion_b: "1816",
  opcion_c: "1806",
  respuesta_correcta: "a"
},
{
  pregunta: "¿Quién fue el primer presidente argentino?",
  categoria: "Historia",
  opcion_a: "Domingo Faustino Sarmiento",
  opcion_b: "Bernardino Rivadavia",
  opcion_c: "Julio Argentino Roca",
  respuesta_correcta: "b"
},
{
  pregunta: "¿Contra qué país fue la Guerra de Malvinas?",
  categoria: "Historia",
  opcion_a: "Estados Unidos",
  opcion_b: "Chile",
  opcion_c: "Reino Unido",
  respuesta_correcta: "c"
},
{
  pregunta: "¿En qué año se declaró la independencia argentina?",
  categoria: "Historia",
  opcion_a: "1810",
  opcion_b: "1816",
  opcion_c: "1820",
  respuesta_correcta: "b"
},

/* =======================
   DEPORTES
======================= */
{
  pregunta: "¿Cuántos jugadores hay en un equipo de fútbol?",
  categoria: "Deportes",
  opcion_a: "10",
  opcion_b: "11",
  opcion_c: "12",
  respuesta_correcta: "b"
},
{
  pregunta: "¿Qué selección ganó el Mundial 2022?",
  categoria: "Deportes",
  opcion_a: "Francia",
  opcion_b: "Brasil",
  opcion_c: "Argentina",
  respuesta_correcta: "c"
},
{
  pregunta: "¿En qué deporte se usa la raqueta?",
  categoria: "Deportes",
  opcion_a: "Tenis",
  opcion_b: "Fútbol",
  opcion_c: "Boxeo",
  respuesta_correcta: "a"
},
{
  pregunta: "¿Quién es conocido como 'La Pulga'?",
  categoria: "Deportes",
  opcion_a: "Diego Maradona",
  opcion_b: "Lionel Messi",
  opcion_c: "Carlos Tevez",
  respuesta_correcta: "b"
},

/* =======================
   GEOGRAFÍA
======================= */
{
  pregunta: "¿Cuál es la capital de Argentina?",
  categoria: "Geografía",
  opcion_a: "Rosario",
  opcion_b: "Córdoba",
  opcion_c: "Buenos Aires",
  respuesta_correcta: "c"
},
{
  pregunta: "¿En qué continente está Argentina?",
  categoria: "Geografía",
  opcion_a: "Europa",
  opcion_b: "América",
  opcion_c: "África",
  respuesta_correcta: "b"
},
{
  pregunta: "¿Cuál es el río más largo de Argentina?",
  categoria: "Geografía",
  opcion_a: "Río Paraná",
  opcion_b: "Río Uruguay",
  opcion_c: "Río Colorado",
  respuesta_correcta: "a"
},
{
  pregunta: "¿Qué océano baña la costa argentina?",
  categoria: "Geografía",
  opcion_a: "Pacífico",
  opcion_b: "Índico",
  opcion_c: "Atlántico",
  respuesta_correcta: "c"
},

/* =======================
   ENTRETENIMIENTO
======================= */
{
  pregunta: "¿Qué personaje dice 'Yo soy tu padre'?",
  categoria: "Entretenimiento",
  opcion_a: "Darth Vader",
  opcion_b: "Yoda",
  opcion_c: "Luke Skywalker",
  respuesta_correcta: "a"
},
{
  pregunta: "¿Qué serie tiene dragones y casas nobles?",
  categoria: "Entretenimiento",
  opcion_a: "Breaking Bad",
  opcion_b: "Game of Thrones",
  opcion_c: "Vikings",
  respuesta_correcta: "b"
},
{
  pregunta: "¿Quién canta 'Muchachos'?",
  categoria: "Entretenimiento",
  opcion_a: "La Mosca",
  opcion_b: "Los Auténticos Decadentes",
  opcion_c: "Los Palmeras",
  respuesta_correcta: "a"
},
{
  pregunta: "¿Qué red social se caracteriza por videos cortos?",
  categoria: "Entretenimiento",
  opcion_a: "Facebook",
  opcion_b: "TikTok",
  opcion_c: "LinkedIn",
  respuesta_correcta: "b"
},

/* =======================
   CIENCIA
======================= */
{
  pregunta: "¿Cuántos planetas tiene el sistema solar?",
  categoria: "Ciencia",
  opcion_a: "7",
  opcion_b: "8",
  opcion_c: "9",
  respuesta_correcta: "b"
},
{
  pregunta: "¿Qué órgano bombea la sangre?",
  categoria: "Ciencia",
  opcion_a: "Pulmón",
  opcion_b: "Cerebro",
  opcion_c: "Corazón",
  respuesta_correcta: "c"
},
{
  pregunta: "¿El agua hierve a cuántos grados centígrados?",
  categoria: "Ciencia",
  opcion_a: "90",
  opcion_b: "100",
  opcion_c: "110",
  respuesta_correcta: "b"
},
{
  pregunta: "¿Qué gas necesitamos para respirar?",
  categoria: "Ciencia",
  opcion_a: "Oxígeno",
  opcion_b: "Dióxido de carbono",
  opcion_c: "Nitrógeno",
  respuesta_correcta: "a"
},
{pregunta:"¿Cuál es el símbolo químico del oro?",categoria:"Ciencia",opcion_a:"Au",opcion_b:"Ag",opcion_c:"O",respuesta_correcta:"a"},
{pregunta:"¿Qué planeta es conocido como el planeta rojo?",categoria:"Ciencia",opcion_a:"Venus",opcion_b:"Marte",opcion_c:"Júpiter",respuesta_correcta:"b"},
{pregunta:"¿Cuántos huesos tiene el cuerpo humano adulto?",categoria:"Ciencia",opcion_a:"206",opcion_b:"210",opcion_c:"198",respuesta_correcta:"a"},
{pregunta:"¿Qué vitamina obtenemos del sol?",categoria:"Ciencia",opcion_a:"Vitamina A",opcion_b:"Vitamina C",opcion_c:"Vitamina D",respuesta_correcta:"c"},
{pregunta:"¿Qué país ganó el Mundial 2014?",categoria:"Deportes",opcion_a:"Brasil",opcion_b:"Alemania",opcion_c:"Argentina",respuesta_correcta:"b"},
{pregunta:"¿En qué deporte se usa un aro y una pelota naranja?",categoria:"Deportes",opcion_a:"Handball",opcion_b:"Vóley",opcion_c:"Básquet",respuesta_correcta:"c"},
{pregunta:"¿Cuántos sets se necesitan para ganar un partido de tenis profesional?",categoria:"Deportes",opcion_a:"Dos",opcion_b:"Tres",opcion_c:"Cuatro",respuesta_correcta:"b"},
{pregunta:"¿Qué selección ganó la Copa América 2021?",categoria:"Deportes",opcion_a:"Brasil",opcion_b:"Argentina",opcion_c:"Uruguay",respuesta_correcta:"b"},
{pregunta:"¿Quién pintó la Mona Lisa?",categoria:"Cultura General",opcion_a:"Picasso",opcion_b:"Da Vinci",opcion_c:"Van Gogh",respuesta_correcta:"b"},
{pregunta:"¿Cuántos días tiene un año bisiesto?",categoria:"Cultura General",opcion_a:"365",opcion_b:"366",opcion_c:"364",respuesta_correcta:"b"},
{pregunta:"¿Cuál es el animal terrestre más grande?",categoria:"Cultura General",opcion_a:"Elefante",opcion_b:"Jirafa",opcion_c:"Hipopótamo",respuesta_correcta:"a"},
{pregunta:"¿Cuál es el continente más grande?",categoria:"Geografía",opcion_a:"África",opcion_b:"Europa",opcion_c:"Asia",respuesta_correcta:"c"},
{pregunta:"¿Qué país tiene forma de bota?",categoria:"Geografía",opcion_a:"España",opcion_b:"Italia",opcion_c:"Grecia",respuesta_correcta:"b"},
{pregunta:"¿Cuál es el país más grande del mundo?",categoria:"Geografía",opcion_a:"Canadá",opcion_b:"China",opcion_c:"Rusia",respuesta_correcta:"c"},
{pregunta:"¿Dónde se encuentra la Torre Eiffel?",categoria:"Geografía",opcion_a:"Roma",opcion_b:"Madrid",opcion_c:"París",respuesta_correcta:"c"},
{pregunta:"¿Quién fue el creador de Facebook?",categoria:"Cultura General",opcion_a:"Bill Gates",opcion_b:"Mark Zuckerberg",opcion_c:"Steve Jobs",respuesta_correcta:"b"},
{pregunta:"¿Cuál es la capital de Brasil?",categoria:"Geografía",opcion_a:"Río de Janeiro",opcion_b:"Brasilia",opcion_c:"San Pablo",respuesta_correcta:"b"},
{pregunta:"¿Qué instrumento tiene teclas blancas y negras?",categoria:"Entretenimiento",opcion_a:"Guitarra",opcion_b:"Piano",opcion_c:"Violín",respuesta_correcta:"b"},
{pregunta:"¿Qué película tiene dinosaurios creados con ADN?",categoria:"Entretenimiento",opcion_a:"King Kong",opcion_b:"Jurassic Park",opcion_c:"Avatar",respuesta_correcta:"b"},
{pregunta:"¿Qué superhéroe es millonario sin poderes?",categoria:"Entretenimiento",opcion_a:"Batman",opcion_b:"Superman",opcion_c:"Flash",respuesta_correcta:"a"},
{pregunta:"¿Quién dirigió la película Titanic?",categoria:"Entretenimiento",opcion_a:"Steven Spielberg",opcion_b:"James Cameron",opcion_c:"Christopher Nolan",respuesta_correcta:"b"},
{pregunta:"¿En qué año llegó el hombre a la Luna?",categoria:"Historia",opcion_a:"1965",opcion_b:"1969",opcion_c:"1972",respuesta_correcta:"b"},
{pregunta:"¿Quién fue el Libertador de América?",categoria:"Historia",opcion_a:"Simón Bolívar",opcion_b:"José de San Martín",opcion_c:"Ambos",respuesta_correcta:"c"},
{pregunta:"¿Qué civilización construyó las pirámides?",categoria:"Historia",opcion_a:"Romanos",opcion_b:"Egipcios",opcion_c:"Griegos",respuesta_correcta:"b"},
{pregunta:"¿Quién fue Eva Perón?",categoria:"Historia",opcion_a:"Actriz y política",opcion_b:"Presidenta",opcion_c:"Militar",respuesta_correcta:"a"},
{pregunta:"¿Qué red social compró Elon Musk?",categoria:"Cultura General",opcion_a:"Facebook",opcion_b:"Instagram",opcion_c:"Twitter",respuesta_correcta:"c"},
{pregunta:"¿Qué animal es símbolo de Australia?",categoria:"Geografía",opcion_a:"Koala",opcion_b:"Canguro",opcion_c:"Emú",respuesta_correcta:"b"},
{pregunta:"¿Cuál es el metal más liviano?",categoria:"Ciencia",opcion_a:"Hierro",opcion_b:"Aluminio",opcion_c:"Litio",respuesta_correcta:"c"},
{pregunta:"¿Qué deporte practica Lionel Messi?",categoria:"Deportes",opcion_a:"Tenis",opcion_b:"Fútbol",opcion_c:"Rugby",respuesta_correcta:"b"},
{pregunta:"¿Qué país es famoso por el sushi?",categoria:"Cultura General",opcion_a:"China",opcion_b:"Corea",opcion_c:"Japón",respuesta_correcta:"c"},
{pregunta:"¿Cuál es la capital de Argentina?",categoria:"Geografía",opcion_a:"Rosario",opcion_b:"Buenos Aires",opcion_c:"Córdoba",respuesta_correcta:"b"},
{pregunta:"¿Qué moneda se usa en Argentina?",categoria:"Cultura General",opcion_a:"Peso",opcion_b:"Real",opcion_c:"Dólar",respuesta_correcta:"a"},
{pregunta:"¿Quién escribió Don Quijote de la Mancha?",categoria:"Cultura General",opcion_a:"Miguel de Cervantes",opcion_b:"Gabriel García Márquez",opcion_c:"Pablo Neruda",respuesta_correcta:"a"},
{pregunta:"¿Qué océano baña la costa argentina?",categoria:"Geografía",opcion_a:"Pacífico",opcion_b:"Atlántico",opcion_c:"Índico",respuesta_correcta:"b"},
{pregunta:"¿Cuántos jugadores hay en un equipo de fútbol?",categoria:"Deportes",opcion_a:"9",opcion_b:"10",opcion_c:"11",respuesta_correcta:"c"},
{pregunta:"¿Qué animal es el rey de la selva?",categoria:"Cultura General",opcion_a:"Tigre",opcion_b:"León",opcion_c:"Elefante",respuesta_correcta:"b"},
{pregunta:"¿Cuál es el río más largo del mundo?",categoria:"Geografía",opcion_a:"Nilo",opcion_b:"Amazonas",opcion_c:"Yangtsé",respuesta_correcta:"b"},
{pregunta:"¿Quién fue el primer presidente argentino?",categoria:"Historia",opcion_a:"Bernardino Rivadavia",opcion_b:"Julio A. Roca",opcion_c:"Domingo Faustino Sarmiento",respuesta_correcta:"a"},
{pregunta:"¿Qué selección ganó el Mundial 2022?",categoria:"Deportes",opcion_a:"Francia",opcion_b:"Brasil",opcion_c:"Argentina",respuesta_correcta:"c"},
{pregunta:"¿Qué gas respiramos principalmente?",categoria:"Ciencia",opcion_a:"Oxígeno",opcion_b:"Nitrógeno",opcion_c:"Dióxido de carbono",respuesta_correcta:"b"},
{pregunta:"¿Qué instrumento se usa para medir la temperatura?",categoria:"Ciencia",opcion_a:"Barómetro",opcion_b:"Termómetro",opcion_c:"Higrómetro",respuesta_correcta:"b"},
{pregunta:"¿En qué continente está Egipto?",categoria:"Geografía",opcion_a:"Asia",opcion_b:"África",opcion_c:"Europa",respuesta_correcta:"b"},
{pregunta:"¿Quién pintó el Guernica?",categoria:"Cultura General",opcion_a:"Dalí",opcion_b:"Picasso",opcion_c:"Goya",respuesta_correcta:"b"},
{pregunta:"¿Qué deporte se juega en Wimbledon?",categoria:"Deportes",opcion_a:"Tenis",opcion_b:"Golf",opcion_c:"Críquet",respuesta_correcta:"a"},
{pregunta:"¿Qué día se celebra la Revolución de Mayo?",categoria:"Historia",opcion_a:"25 de mayo",opcion_b:"9 de julio",opcion_c:"20 de junio",respuesta_correcta:"a"},
{pregunta:"¿Cuál es el metal más usado en latas?",categoria:"Ciencia",opcion_a:"Hierro",opcion_b:"Aluminio",opcion_c:"Cobre",respuesta_correcta:"b"},
{pregunta:"¿Qué país inventó la pizza?",categoria:"Cultura General",opcion_a:"Francia",opcion_b:"Italia",opcion_c:"España",respuesta_correcta:"b"},
{pregunta:"¿Cuál es el idioma más hablado del mundo?",categoria:"Cultura General",opcion_a:"Inglés",opcion_b:"Español",opcion_c:"Chino mandarín",respuesta_correcta:"c"},
{pregunta:"¿Quién protagonizó Forrest Gump?",categoria:"Entretenimiento",opcion_a:"Brad Pitt",opcion_b:"Tom Hanks",opcion_c:"Leonardo DiCaprio",respuesta_correcta:"b"},
{pregunta:"¿Qué planeta es el más grande del sistema solar?",categoria:"Ciencia",opcion_a:"Saturno",opcion_b:"Júpiter",opcion_c:"Neptuno",respuesta_correcta:"b"},
{pregunta:"¿Qué selección tiene más Copas del Mundo?",categoria:"Deportes",opcion_a:"Alemania",opcion_b:"Brasil",opcion_c:"Italia",respuesta_correcta:"b"},
{pregunta:"¿En qué año fue la independencia argentina?",categoria:"Historia",opcion_a:"1810",opcion_b:"1816",opcion_c:"1820",respuesta_correcta:"b"},
{pregunta:"¿Qué instrumento mide la presión atmosférica?",categoria:"Ciencia",opcion_a:"Barómetro",opcion_b:"Termómetro",opcion_c:"Anemómetro",respuesta_correcta:"a"},
{pregunta:"¿Cuál es la montaña más alta del mundo?",categoria:"Geografía",opcion_a:"Aconcagua",opcion_b:"Everest",opcion_c:"K2",respuesta_correcta:"b"},
{pregunta:"¿Quién canta la canción Color Esperanza?",categoria:"Entretenimiento",opcion_a:"Fito Páez",opcion_b:"Diego Torres",opcion_c:"Andrés Calamaro",respuesta_correcta:"b"},
{pregunta:"¿Qué animal representa el escudo argentino?",categoria:"Cultura General",opcion_a:"Cóndor",opcion_b:"León",opcion_c:"No tiene animal",respuesta_correcta:"c"},
{pregunta:"¿Qué deporte practicaba Diego Maradona?",categoria:"Deportes",opcion_a:"Básquet",opcion_b:"Fútbol",opcion_c:"Tenis",respuesta_correcta:"b"},
{pregunta:"¿Qué órgano bombea la sangre?",categoria:"Ciencia",opcion_a:"Pulmón",opcion_b:"Cerebro",opcion_c:"Corazón",respuesta_correcta:"c"},
{pregunta:"¿Qué país limita con Argentina al oeste?",categoria:"Geografía",opcion_a:"Uruguay",opcion_b:"Chile",opcion_c:"Paraguay",respuesta_correcta:"b"},
{pregunta:"¿Quién fue Manuel Belgrano?",categoria:"Historia",opcion_a:"Militar y creador de la bandera",opcion_b:"Presidente",opcion_c:"Escritor",respuesta_correcta:"a"},
{pregunta:"¿Cuál es el río más importante de Argentina?",categoria:"Geografía",opcion_a:"Paraná",opcion_b:"Uruguay",opcion_c:"Colorado",respuesta_correcta:"a"},
{pregunta:"¿Qué prócer creó la bandera argentina?",categoria:"Historia",opcion_a:"San Martín",opcion_b:"Belgrano",opcion_c:"Rivadavia",respuesta_correcta:"b"},
{pregunta:"¿Cuántas provincias tiene Argentina?",categoria:"Cultura General",opcion_a:"22",opcion_b:"23",opcion_c:"24",respuesta_correcta:"b"},
{pregunta:"¿Qué selección ganó el Mundial 1986?",categoria:"Deportes",opcion_a:"Brasil",opcion_b:"Alemania",opcion_c:"Argentina",respuesta_correcta:"c"},
{pregunta:"¿Qué órgano permite respirar?",categoria:"Ciencia",opcion_a:"Pulmones",opcion_b:"Riñones",opcion_c:"Corazón",respuesta_correcta:"a"},
{pregunta:"¿Cuál es la capital de Uruguay?",categoria:"Geografía",opcion_a:"Punta del Este",opcion_b:"Montevideo",opcion_c:"Colonia",respuesta_correcta:"b"},
{pregunta:"¿Qué deporte se juega con raqueta y red?",categoria:"Deportes",opcion_a:"Tenis",opcion_b:"Hockey",opcion_c:"Golf",respuesta_correcta:"a"},
{pregunta:"¿Quién escribió El Principito?",categoria:"Cultura General",opcion_a:"Julio Verne",opcion_b:"Antoine de Saint-Exupéry",opcion_c:"Victor Hugo",respuesta_correcta:"b"},
{pregunta:"¿Qué gas es necesario para la combustión?",categoria:"Ciencia",opcion_a:"Oxígeno",opcion_b:"Nitrógeno",opcion_c:"Hidrógeno",respuesta_correcta:"a"},
{pregunta:"¿Qué país ganó el Mundial 2010?",categoria:"Deportes",opcion_a:"Alemania",opcion_b:"España",opcion_c:"Italia",respuesta_correcta:"b"},
{pregunta:"¿Qué continente está Argentina?",categoria:"Geografía",opcion_a:"América del Sur",opcion_b:"América Central",opcion_c:"Europa",respuesta_correcta:"a"},
{pregunta:"¿Qué animal produce leche?",categoria:"Ciencia",opcion_a:"Gallina",opcion_b:"Vaca",opcion_c:"Oveja",respuesta_correcta:"b"},
{pregunta:"¿Quién fue el primer hombre en pisar la Luna?",categoria:"Historia",opcion_a:"Buzz Aldrin",opcion_b:"Neil Armstrong",opcion_c:"Yuri Gagarin",respuesta_correcta:"b"},
{pregunta:"¿Qué instrumento se usa para medir el tiempo?",categoria:"Ciencia",opcion_a:"Termómetro",opcion_b:"Reloj",opcion_c:"Barómetro",respuesta_correcta:"b"},
{pregunta:"¿Qué selección ganó el Mundial 1978?",categoria:"Deportes",opcion_a:"Argentina",opcion_b:"Brasil",opcion_c:"Italia",respuesta_correcta:"a"},
{pregunta:"¿Cuál es el idioma oficial de Argentina?",categoria:"Cultura General",opcion_a:"Inglés",opcion_b:"Español",opcion_c:"Portugués",respuesta_correcta:"b"},
{pregunta:"¿Qué país está al norte de Argentina?",categoria:"Geografía",opcion_a:"Chile",opcion_b:"Bolivia",opcion_c:"Uruguay",respuesta_correcta:"b"},
{pregunta:"¿Quién fue Domingo Faustino Sarmiento?",categoria:"Historia",opcion_a:"Presidente y educador",opcion_b:"Militar",opcion_c:"Explorador",respuesta_correcta:"a"},
{pregunta:"¿Qué deporte se juega con once jugadores por equipo?",categoria:"Deportes",opcion_a:"Rugby",opcion_b:"Fútbol",opcion_c:"Hockey",respuesta_correcta:"b"},
{pregunta:"¿Qué planeta está más cerca del Sol?",categoria:"Ciencia",opcion_a:"Venus",opcion_b:"Mercurio",opcion_c:"Marte",respuesta_correcta:"b"},
{pregunta:"¿Cuál es la capital de Chile?",categoria:"Geografía",opcion_a:"Santiago",opcion_b:"Valparaíso",opcion_c:"Concepción",respuesta_correcta:"a"},
{pregunta:"¿Quién cantaba Persiana Americana?",categoria:"Entretenimiento",opcion_a:"Soda Stereo",opcion_b:"Virus",opcion_c:"Los Redondos",respuesta_correcta:"a"},
{pregunta:"¿Qué animal es conocido por su memoria?",categoria:"Cultura General",opcion_a:"Elefante",opcion_b:"Perro",opcion_c:"Delfín",respuesta_correcta:"a"},
{pregunta:"¿Qué elemento químico tiene símbolo H?",categoria:"Ciencia",opcion_a:"Helio",opcion_b:"Hidrógeno",opcion_c:"Hierro",respuesta_correcta:"b"},
{pregunta:"¿Qué país ganó el Mundial 1998?",categoria:"Deportes",opcion_a:"Brasil",opcion_b:"Francia",opcion_c:"Alemania",respuesta_correcta:"b"},
{pregunta:"¿Qué prócer cruzó los Andes?",categoria:"Historia",opcion_a:"Belgrano",opcion_b:"San Martín",opcion_c:"Rosas",respuesta_correcta:"b"},
{pregunta:"¿Cuál es el lago más grande de Argentina?",categoria:"Geografía",opcion_a:"Lago Argentino",opcion_b:"Nahuel Huapi",opcion_c:"Lago Viedma",respuesta_correcta:"a"},
{pregunta:"¿Qué instrumento tiene cuerdas?",categoria:"Entretenimiento",opcion_a:"Batería",opcion_b:"Guitarra",opcion_c:"Trompeta",respuesta_correcta:"b"},
{pregunta:"¿Qué parte del cuerpo usamos para pensar?",categoria:"Ciencia",opcion_a:"Corazón",opcion_b:"Cerebro",opcion_c:"Pulmón",respuesta_correcta:"b"},
{pregunta:"¿Qué país limita con Argentina al este?",categoria:"Geografía",opcion_a:"Chile",opcion_b:"Uruguay",opcion_c:"Bolivia",respuesta_correcta:"b"},
{pregunta:"¿Quién fue Juan Manuel de Rosas?",categoria:"Historia",opcion_a:"Gobernador de Buenos Aires",opcion_b:"Explorador",opcion_c:"Poeta",respuesta_correcta:"a"},
{pregunta:"¿Qué deporte se juega con una pelota ovalada?",categoria:"Deportes",opcion_a:"Rugby",opcion_b:"Fútbol",opcion_c:"Básquet",respuesta_correcta:"a"},
{pregunta:"¿Cuál es la capital de la provincia de Córdoba?",categoria:"Geografía",opcion_a:"Río Cuarto",opcion_b:"Córdoba",opcion_c:"Villa Carlos Paz",respuesta_correcta:"b"},
{pregunta:"¿En qué año volvió la democracia a Argentina?",categoria:"Historia",opcion_a:"1976",opcion_b:"1983",opcion_c:"1990",respuesta_correcta:"b"},
{pregunta:"¿Cuántos jugadores hay en una cancha de básquet?",categoria:"Deportes",opcion_a:"5 por equipo",opcion_b:"6 por equipo",opcion_c:"7 por equipo",respuesta_correcta:"a"},
{pregunta:"¿Qué provincia es conocida como La Tierra del Fuego?",categoria:"Geografía",opcion_a:"Santa Cruz",opcion_b:"Chubut",opcion_c:"Tierra del Fuego",respuesta_correcta:"c"},
{pregunta:"¿Qué instrumento mide la temperatura?",categoria:"Ciencia",opcion_a:"Barómetro",opcion_b:"Termómetro",opcion_c:"Anemómetro",respuesta_correcta:"b"},
{pregunta:"¿Quién fue el primer presidente argentino?",categoria:"Historia",opcion_a:"Rivadavia",opcion_b:"Urquiza",opcion_c:"Sarmiento",respuesta_correcta:"a"},
{pregunta:"¿Qué selección ganó el Mundial 2022?",categoria:"Deportes",opcion_a:"Francia",opcion_b:"Argentina",opcion_c:"Croacia",respuesta_correcta:"b"},
{pregunta:"¿Qué océano baña la costa argentina?",categoria:"Geografía",opcion_a:"Pacífico",opcion_b:"Atlántico",opcion_c:"Índico",respuesta_correcta:"b"},
{pregunta:"¿Qué planeta es conocido como el planeta rojo?",categoria:"Ciencia",opcion_a:"Venus",opcion_b:"Marte",opcion_c:"Júpiter",respuesta_correcta:"b"},
{pregunta:"¿Quién escribió Martín Fierro?",categoria:"Cultura General",opcion_a:"Borges",opcion_b:"José Hernández",opcion_c:"Cortázar",respuesta_correcta:"b"},
{pregunta:"¿Cuántos minutos dura un partido de fútbol profesional?",categoria:"Deportes",opcion_a:"80",opcion_b:"90",opcion_c:"100",respuesta_correcta:"b"},
{pregunta:"¿Qué país limita con Argentina al oeste?",categoria:"Geografía",opcion_a:"Uruguay",opcion_b:"Chile",opcion_c:"Paraguay",respuesta_correcta:"b"},
{pregunta:"¿Qué sangre es donante universal?",categoria:"Ciencia",opcion_a:"AB+",opcion_b:"O-",opcion_c:"A+",respuesta_correcta:"b"},
{pregunta:"¿Qué prócer argentino fue creador del Ejército de los Andes?",categoria:"Historia",opcion_a:"Belgrano",opcion_b:"San Martín",opcion_c:"Güemes",respuesta_correcta:"b"},
{pregunta:"¿Qué deporte practica Lionel Messi?",categoria:"Deportes",opcion_a:"Tenis",opcion_b:"Fútbol",opcion_c:"Básquet",respuesta_correcta:"b"},
{pregunta:"¿Cuál es la capital de Mendoza?",categoria:"Geografía",opcion_a:"San Rafael",opcion_b:"Godoy Cruz",opcion_c:"Mendoza",respuesta_correcta:"c"},
{pregunta:"¿Qué órgano bombea la sangre?",categoria:"Ciencia",opcion_a:"Pulmón",opcion_b:"Cerebro",opcion_c:"Corazón",respuesta_correcta:"c"},
{pregunta:"¿Qué guerra marcó el final del gobierno militar en Argentina?",categoria:"Historia",opcion_a:"Guerra del Paraguay",opcion_b:"Guerra de Malvinas",opcion_c:"Guerra Fría",respuesta_correcta:"b"},
{pregunta:"¿Cuántos sets se juegan en un partido de tenis profesional?",categoria:"Deportes",opcion_a:"3 o 5",opcion_b:"2",opcion_c:"4",respuesta_correcta:"a"},
{pregunta:"¿Cuál es el río que separa Argentina y Uruguay?",categoria:"Geografía",opcion_a:"Paraná",opcion_b:"Río de la Plata",opcion_c:"Uruguay",respuesta_correcta:"c"},
{pregunta:"¿Qué vitamina obtenemos del sol?",categoria:"Ciencia",opcion_a:"Vitamina A",opcion_b:"Vitamina C",opcion_c:"Vitamina D",respuesta_correcta:"c"},
{pregunta:"¿Quién fue Eva Perón?",categoria:"Historia",opcion_a:"Primera dama",opcion_b:"Presidenta",opcion_c:"Militar",respuesta_correcta:"a"},
{pregunta:"¿Qué deporte se juega en Roland Garros?",categoria:"Deportes",opcion_a:"Tenis",opcion_b:"Fútbol",opcion_c:"Rugby",respuesta_correcta:"a"},
{pregunta:"¿Qué provincia argentina tiene salida al mar?",categoria:"Geografía",opcion_a:"Córdoba",opcion_b:"La Pampa",opcion_c:"Buenos Aires",respuesta_correcta:"c"},
{pregunta:"¿Qué gas respiramos principalmente?",categoria:"Ciencia",opcion_a:"Oxígeno",opcion_b:"Nitrógeno",opcion_c:"Dióxido de carbono",respuesta_correcta:"b"},
{pregunta:"¿Qué escritor argentino escribió Rayuela?",categoria:"Cultura General",opcion_a:"Borges",opcion_b:"Cortázar",opcion_c:"Sabato",respuesta_correcta:"b"},
{pregunta:"¿Cuántos jugadores hay en un equipo de vóley?",categoria:"Deportes",opcion_a:"5",opcion_b:"6",opcion_c:"7",respuesta_correcta:"b"},
{pregunta:"¿Qué provincia es la más poblada de Argentina?",categoria:"Geografía",opcion_a:"Santa Fe",opcion_b:"Córdoba",opcion_c:"Buenos Aires",respuesta_correcta:"c"},
{pregunta:"¿Qué parte del cuerpo humano tiene más huesos?",categoria:"Ciencia",opcion_a:"Mano",opcion_b:"Pie",opcion_c:"Columna",respuesta_correcta:"a"},
{pregunta:"¿Qué famoso cantante argentino fue conocido como 'El Flaco'?",categoria:"Entretenimiento",opcion_a:"Carlos Gardel",opcion_b:"Luis Alberto Spinetta",opcion_c:"Charly García",respuesta_correcta:"b"},
{pregunta:"¿Qué famoso programa de televisión argentino se emitió por primera vez en 2001 y estuvo a cargo de Ricardo Fort?",categoria:"Entretenimiento",opcion_a:"Gran Hermano",opcion_b:"Showmatch",opcion_c:"Fort Night",respuesta_correcta:"c"},
{pregunta:"¿Qué novela argentina de 2002 protagonizada por Juana Viale fue un éxito internacional?",categoria:"Entretenimiento",opcion_a:"Chiquititas",opcion_b:"Los Exitosos Pells",opcion_c:"Ricos y Famosos",respuesta_correcta:"b"},
{pregunta:"¿En qué año empezó a emitirse la serie argentina 'Casi Ángeles'?",categoria:"Entretenimiento",opcion_a:"2001",opcion_b:"2004",opcion_c:"2007",respuesta_correcta:"b"},
{pregunta:"¿Qué famosa banda de rock argentina lanzó el álbum 'Canción Animal' en 1990?",categoria:"Entretenimiento",opcion_a:"Spinetta",opcion_b:"Soda Stereo",opcion_c:"Patricio Rey y sus Redonditos de Ricota",respuesta_correcta:"b"},
{pregunta:"¿Cuál fue la primer telenovela de Cris Morena que se emitió en la Argentina en 1998?",categoria:"Entretenimiento",opcion_a:"Chiquititas",opcion_b:"Casi Ángeles",opcion_c:"Verano del 98",respuesta_correcta:"a"},
{pregunta:"¿Qué importante evento deportivo se llevó a cabo en Argentina en 1978?",categoria:"Deportes",opcion_a:"Copa América",opcion_b:"Mundial de Fútbol",opcion_c:"Copa del Mundo de Rugby",respuesta_correcta:"b"},
{pregunta:"¿En qué año Argentina ganó la Copa del Mundo de fútbol por segunda vez?",categoria:"Deportes",opcion_a:"1990",opcion_b:"2006",opcion_c:"1986",respuesta_correcta:"c"},
{pregunta:"¿Qué equipo de fútbol argentino ganó la Copa Libertadores 2003?",categoria:"Deportes",opcion_a:"Boca Juniors",opcion_b:"River Plate",opcion_c:"Independiente",respuesta_correcta:"a"},
{pregunta:"¿Qué jugador argentino ganó el Balón de Oro en 2009?",categoria:"Deportes",opcion_a:"Lionel Messi",opcion_b:"Carlos Tévez",opcion_c:"Diego Maradona",respuesta_correcta:"a"},
{pregunta:"¿Qué deporte se destacó entre los argentinos en los años 2000 por su éxito en los Juegos Olímpicos?",categoria:"Deportes",opcion_a:"Rugby",opcion_b:"Fútbol",opcion_c:"Hockey",respuesta_correcta:"c"},
{pregunta:"¿Qué evento internacional de ciclismo se celebra anualmente en Argentina?",categoria:"Deportes",opcion_a:"Tour de Francia",opcion_b:"Vuelta de España",opcion_c:"Tour de San Juan",respuesta_correcta:"c"},
{pregunta:"¿Cuál es la selección nacional más ganadora en la historia de los Juegos Panamericanos?",categoria:"Deportes",opcion_a:"Argentina",opcion_b:"Brasil",opcion_c:"México",respuesta_correcta:"a"},
{pregunta:"¿En qué ciudad argentina se disputó la Copa Mundial de Fútbol 1978?",categoria:"Deportes",opcion_a:"Córdoba",opcion_b:"Rosario",opcion_c:"Buenos Aires",respuesta_correcta:"c"},
{pregunta:"¿Quién ganó el premio Nobel de la Paz en 1980?",categoria:"Cultura General",opcion_a:"Nelson Mandela",opcion_b:"Adolfo Pérez Esquivel",opcion_c:"Albert Einstein",respuesta_correcta:"b"},
{pregunta:"¿Qué importante acontecimiento mundial ocurrió en 2001?",categoria:"Cultura General",opcion_a:"La caída del Muro de Berlín",opcion_b:"Los atentados del 11 de septiembre",opcion_c:"La guerra de Irak",respuesta_correcta:"b"},
{pregunta:"¿Qué país fue el primero en enviar una misión tripulada a la Luna?",categoria:"Cultura General",opcion_a:"Estados Unidos",opcion_b:"Rusia",opcion_c:"China",respuesta_correcta:"a"},
{pregunta:"¿Qué famoso líder sudamericano fue conocido como 'El Libertador'?",categoria:"Cultura General",opcion_a:"Simón Bolívar",opcion_b:"José de San Martín",opcion_c:"Che Guevara",respuesta_correcta:"a"},
{pregunta:"¿Qué evento histórico ocurrió en 2008 en la Argentina, relacionado con el conflicto entre el gobierno y las entidades rurales?",categoria:"Cultura General",opcion_a:"La crisis económica",opcion_b:"El conflicto por la 125",opcion_c:"El estallido social",respuesta_correcta:"b"},
{pregunta:"¿Qué presidenta argentina asumió el poder en 2007?",categoria:"Cultura General",opcion_a:"Cristina Fernández de Kirchner",opcion_b:"Máxima de Holanda",opcion_c:"María Estela Martínez de Perón",respuesta_correcta:"a"},
{pregunta:"¿Qué país recibió la Copa del Mundo en 2006?",categoria:"Cultura General",opcion_a:"Francia",opcion_b:"Italia",opcion_c:"España",respuesta_correcta:"b"},
{pregunta:"¿Qué famoso escritor argentino murió en 1986?",categoria:"Cultura General",opcion_a:"Jorge Luis Borges",opcion_b:"Ernesto Sabato",opcion_c:"Adolfo Bioy Casares",respuesta_correcta:"a"},
{pregunta:"¿Quién fue el primer presidente de la democracia argentina después de la dictadura?",categoria:"Cultura General",opcion_a:"Carlos Menem",opcion_b:"Raúl Alfonsín",opcion_c:"Fernando de la Rúa",respuesta_correcta:"b"},
{pregunta:"¿Qué país sudamericano fue el primero en obtener independencia?",categoria:"Cultura General",opcion_a:"Perú",opcion_b:"Colombia",opcion_c:"Venezuela",respuesta_correcta:"c"},
{pregunta:"¿Qué conflicto internacional involucró a las Malvinas en 1982?",categoria:"Cultura General",opcion_a:"La guerra con Chile",opcion_b:"La guerra con Reino Unido",opcion_c:"La guerra de las Malvinas",respuesta_correcta:"b"},
{pregunta:"¿Qué físico argentino ganó el premio Nobel de Física en 1962?",categoria:"Cultura General",opcion_a:"Juan José Giacobone",opcion_b:"Luis Federico Leloir",opcion_c:"César Milstein",respuesta_correcta:"c"},
{pregunta:"¿Qué reality show se estrenó en Argentina en 2001 y fue un fenómeno social?",categoria:"Entretenimiento",opcion_a:"Operación Triunfo",opcion_b:"Gran Hermano",opcion_c:"Expedición Robinson",respuesta_correcta:"b"},
{pregunta:"¿Quién fue el primer ganador de Gran Hermano Argentina?",categoria:"Entretenimiento",opcion_a:"Gastón Trezeguet",opcion_b:"Marcelo Corazza",opcion_c:"Tamara Paganini",respuesta_correcta:"b"},
{pregunta:"¿Qué conductor estuvo al frente de Videomatch en los años 2000?",categoria:"Entretenimiento",opcion_a:"Guido Kaczka",opcion_b:"Marcelo Tinelli",opcion_c:"Adrián Suar",respuesta_correcta:"b"},
{pregunta:"¿Qué programa argentino mostraba cámaras ocultas y bromas pesadas?",categoria:"Entretenimiento",opcion_a:"VideoMatch",opcion_b:"Caiga Quien Caiga",opcion_c:"Justo a Tiempo",respuesta_correcta:"a"},
{pregunta:"¿Qué actriz protagonizó la película argentina 'Nueve Reinas'?",categoria:"Entretenimiento",opcion_a:"Valeria Bertuccelli",opcion_b:"Griselda Siciliani",opcion_c:"No tuvo protagonista femenina principal",respuesta_correcta:"c"},
{pregunta:"¿Qué actor protagonizó 'Nueve Reinas' junto a Ricardo Darín?",categoria:"Entretenimiento",opcion_a:"Leonardo Sbaraglia",opcion_b:"Gastón Pauls",opcion_c:"Pablo Echarri",respuesta_correcta:"a"},
{pregunta:"¿Cómo se llamaba el programa de chimentos conducido por Jorge Rial?",categoria:"Entretenimiento",opcion_a:"Intrusos",opcion_b:"RSM",opcion_c:"Indomables",respuesta_correcta:"a"},
{pregunta:"¿En qué canal se emitía 'Intrusos' originalmente?",categoria:"Entretenimiento",opcion_a:"Telefe",opcion_b:"Canal 9",opcion_c:"América",respuesta_correcta:"c"},
{pregunta:"¿Qué programa satírico se emitía los domingos y criticaba a los medios?",categoria:"Entretenimiento",opcion_a:"Caiga Quien Caiga",opcion_b:"Perros de la Calle",opcion_c:"La TV Ataca",respuesta_correcta:"a"},
{pregunta:"¿Qué actor argentino fue galán de telenovelas en los 2000 como 'Resistiré'?",categoria:"Entretenimiento",opcion_a:"Pablo Echarri",opcion_b:"Facundo Arana",opcion_c:"Luciano Castro",respuesta_correcta:"a"},
{pregunta:"¿Qué novela protagonizó Natalia Oreiro a comienzos de los 2000?",categoria:"Entretenimiento",opcion_a:"Muñeca Brava",opcion_b:"Rebelde Way",opcion_c:"Floricienta",respuesta_correcta:"a"},
{pregunta:"¿Qué serie juvenil mostraba un colegio secundario y se estrenó en 2002?",categoria:"Entretenimiento",opcion_a:"Rebelde Way",opcion_b:"Chiquititas",opcion_c:"Casi Ángeles",respuesta_correcta:"a"},
{pregunta:"¿Qué productora estuvo detrás de muchas ficciones juveniles de los 2000?",categoria:"Entretenimiento",opcion_a:"Pol-ka",opcion_b:"Ideas del Sur",opcion_c:"Cris Morena Group",respuesta_correcta:"c"},
{pregunta:"¿Qué programa de juegos se emitía con participantes anónimos ganando premios?",categoria:"Entretenimiento",opcion_a:"Trato Hecho",opcion_b:"Sorpresa y Media",opcion_c:"Fort Boyard",respuesta_correcta:"a"},
{pregunta:"¿Quién conducía 'Trato Hecho' en Argentina?",categoria:"Entretenimiento",opcion_a:"Julián Weich",opcion_b:"Mariano Iúdica",opcion_c:"Guillermo Andino",respuesta_correcta:"a"},
{pregunta:"¿Qué actor argentino se destacó en cine y TV con papeles intensos en los 2000?",categoria:"Entretenimiento",opcion_a:"Ricardo Darín",opcion_b:"Nicolás Cabré",opcion_c:"Benjamín Vicuña",respuesta_correcta:"a"},
{pregunta:"¿Qué película argentina de 2005 fue protagonizada por Darín y De Francella?",categoria:"Entretenimiento",opcion_a:"El hijo de la novia",opcion_b:"Tiempo de valientes",opcion_c:"Luna de Avellaneda",respuesta_correcta:"b"},
{pregunta:"¿Qué programa mostraba informes irónicos con traje y anteojos negros?",categoria:"Entretenimiento",opcion_a:"Indomables",opcion_b:"Caiga Quien Caiga",opcion_c:"TVR",respuesta_correcta:"b"},
{pregunta:"¿Qué figura mediática se hizo famosa por frases polémicas y excéntricas?",categoria:"Entretenimiento",opcion_a:"Ricardo Fort",opcion_b:"Guido Suller",opcion_c:"Jacobo Winograd",respuesta_correcta:"a"},
{pregunta:"¿Qué reality argentino mezclaba famosos y convivencia?",categoria:"Entretenimiento",opcion_a:"Gran Hermano Famosos",opcion_b:"Bailando por un Sueño",opcion_c:"El Bar",respuesta_correcta:"a"},
{pregunta:"¿Qué concurso de baile se volvió central en la TV de los 2000?",categoria:"Entretenimiento",opcion_a:"Patinando por un Sueño",opcion_b:"Bailando por un Sueño",opcion_c:"Cantando por un Sueño",respuesta_correcta:"b"},
{pregunta:"¿Qué programa mostraba resúmenes críticos de la semana televisiva?",categoria:"Entretenimiento",opcion_a:"TVR",opcion_b:"RSM",opcion_c:"Duro de Domar",respuesta_correcta:"a"},
{pregunta:"¿Qué conductor se destacó por su estilo irónico en 'RSM'?",categoria:"Entretenimiento",opcion_a:"Mario Pergolini",opcion_b:"Guillermo López",opcion_c:"Andy Kusnetzoff",respuesta_correcta:"b"},
{pregunta:"¿Qué serie argentina mostraba estafas planificadas por un grupo?",categoria:"Entretenimiento",opcion_a:"Hermanos y Detectives",opcion_b:"Los Simuladores",opcion_c:"Vulnerables",respuesta_correcta:"b"}
];
